// The history of Juniper Bay. This is the single source of truth for plaques,
// the almanac, the newspaper, cornerstones, family businesses and what people remember.

export const TOWN = {
  name: 'Juniper Bay',
  founded: 1853,
  population: 'about 31,000 (1950 census: 30,882)',
  motto: 'Steadfast in Fair Weather and Foul',
  nickname: 'The Bay',
  today: 'Saturday, September 26, 1953 — the Centennial "Harbor Days" celebration',
};

// Key streets and what they're named for
export const STREETS = {
  'Harbor Street': 'Runs along the waterfront. Once "the Strand"; renamed in 1872 when the railroad came.',
  'Main Street': 'The oldest road in town — the cart track from Whitcomb\'s wharf up to the timber lots.',
  'Lantern Avenue': 'Named for the whale-oil lanterns that lit the first town hall steps. The trolley has run down its middle since 1906.',
  'Elm Street': 'Lined with elms until the 1938 hurricane took most of them; the maples you see were planted in 1939 by schoolchildren.',
  'Hillcrest Avenue': 'The "captains\' row" — big houses built by skippers and cannery money in the 1880s and 90s.',
  'Mill Street': 'Named for Dunmore\'s sawmill (1856–1911). Now faces Union Station.',
  'Canal Street': 'There was never a canal. An 1860s land company promised one and went bust. The name stuck.',
  'Grand Avenue': 'Laid out in 1874 as the town\'s ceremonial street, ending at City Hall.',
  'Market Street': 'The fish and produce market street. Burned in the Great Fire of 1902; rebuilt in brick.',
  'Church Street': 'Home to St. Brigid\'s and First Congregational, a block apart, which everyone agrees is close enough.',
  'Maple Street': 'Family street — porches, swing sets, pie cooling on sills.',
  'Orchard Street': 'Once the Pruitt apple orchard. A few old trees still stand in back yards.',
};

export const TIMELINE = [
  [1790, 'Seasonal fishing camps on the cove. The trail over Juniper Hill follows a path used by the Massachusett people long before.'],
  [1851, 'Captain Elias Whitcomb shelters his schooner JUNIPER in the cove during an October gale and swears he will come back.'],
  [1853, 'March 4: the town charter is granted. 212 souls. Whitcomb\'s wharf, a salt house, a chapel and eleven houses.'],
  [1856, 'Dunmore\'s sawmill opens on Mill Street. The first Market Street stores follow.'],
  [1859, 'The granite Custom House is built on the waterfront (today the Maritime Museum).'],
  [1861, 'Forty-three Juniper Bay men go to war for the Union. Nine do not come home. The bronze soldier in Founders Square (1889) bears their names.'],
  [1867, 'The Great Gale: the schooner MARY ELLEN is lost off Gannet Ledge with all eleven hands. The fishermen\'s memorial on the quay is raised by their widows.'],
  [1868, 'Whitcomb Point Light is lit for the first time, paid for by public subscription.'],
  [1871, 'First Juniper Savings Bank opens with $4,112 in deposits.'],
  [1872, 'The Boston & Juniper Bay Railroad arrives. Harbor Street gets its name.'],
  [1874, 'Grand Avenue is laid out. City Hall (the "Old Granite Lady") completed in 1876.'],
  [1878, 'Harlow\'s opens as a one-room dry goods shop on Market Street.'],
  [1880, 'Irish families arrive to lay track and work the wharves. St. Brigid\'s parish founded 1882.'],
  [1887, 'Patrick Halloran opens a bakery with one oven and his wife Nora\'s soda bread recipe.'],
  [1889, 'The present Union Station opens, with its great arched train shed.'],
  [1891, 'Portuguese fishermen from the Azores settle along the south wharves. The Blessing of the Fleet begins.'],
  [1894, 'Giuseppe Castellano, from Sciacca, Sicily, founds Castellano Fish Co. with one dory.'],
  [1896, 'The Whitcomb Hotel opens on Mill Street.'],
  [1899, 'Harbor Canning Co. opens. Sardines, mackerel, and the smell everyone pretends not to notice.'],
  [1902, 'The Great Fire of June 11, 1902 starts in Beal\'s livery and burns three blocks of Market Street. No lives lost. Downtown is rebuilt in brick and stone — look for the 1903–1905 cornerstones.'],
  [1903, 'Engine Company No. 1 gets its first steam pumper, "Old Faithful", now retired to the fire station floor.'],
  [1906, 'Isaac Adler opens his tailor shop. The electric trolley begins running on Lantern Avenue.'],
  [1908, 'Polish families come to work the cannery. The Novak and Kowalski families among them.'],
  [1911, 'The Carnegie Library opens. Henry Lee\'s father opens Lee\'s Hand Laundry on Market Street.'],
  [1917, 'Two hundred and twelve men serve in the Great War; nine are lost. Juniper Park\'s oaks were planted for them.'],
  [1918, 'The influenza. City Hall\'s council chamber becomes a hospital ward for six weeks.'],
  [1919, 'Samuel Freeman comes north from Virginia and opens Freeman\'s Barber Shop in 1921.'],
  [1920, 'St. Luke\'s Hospital opens, built by public subscription after the influenza.'],
  [1924, 'Nick Papadakis\'s father opens a lunch counter on Harbor Street.'],
  [1928, 'Radio station WJBY goes on the air from a closet above the bank.'],
  [1929, 'The Juniper Trust Building is finished in October — three weeks before the Crash. The tallest building on the coast between Boston and Portland.'],
  [1932, 'Depression. The cannery cuts shifts; the Hallorans sell day-old bread for a penny and quietly give away the rest.'],
  [1934, 'The Cannery Strike. Nineteen days in July. Casimir Novak, then 29, speaks on the steps of City Hall. The union wins a nickel an hour.'],
  [1936, 'WPA crews build the new seawall and the Juniper Park bandstand.'],
  [1938, 'The Great Hurricane, September 21. Storm surge floods Harbor Street to six feet. Pier 3 is swept away; three lives are lost. High-water marks are painted on buildings along the waterfront. The Harbor Light Diner car is installed that same winter.'],
  [1941, 'Six hundred and forty Juniper Bay men and women serve in the Second World War. Twenty-three are lost. The shipyard builds wooden minesweepers.'],
  [1945, 'V-J Day: the whole town ends up on Founders Square. Church bells ring for an hour.'],
  [1950, 'Korea. Fourteen local boys go. Sal Castellano Jr. comes home in September 1953.'],
  [1953, 'The Centennial. Harbor Days, Saturday September 26: parade, fair, the Mayor\'s address, a time capsule to be opened in 2053, a street dance and fireworks over the harbor.'],
];

// Families and institutions people talk about. (Used for bios, gossip and signage.)
export const FAMILIES = {
  Whitcomb: { origin: 'Founders (English, from Salem)', note: 'Captain Elias Whitcomb founded the town in 1853. His great-granddaughter Miss Augusta Whitcomb, 81, runs the Historical Society and will bury the time capsule.' },
  Halloran: { origin: 'Irish (County Clare), 1880s', note: 'Halloran & Sons Bakery since 1887. Pat Halloran III runs it; wife Irene; children Peggy (16) and Tommy (11); Grandma Bridget (79) saw the Great Fire as a girl. They own the first television set on Church Street.' },
  Castellano: { origin: 'Sicilian (Sciacca), 1894', note: 'Castellano Fish Co. on Pier 3. Sal Sr. and Rosa. Son Sal Jr. just home from Korea — welcome-home supper Saturday night.' },
  Novak: { origin: 'Polish, 1908', note: 'Casimir Novak, cannery foreman and hero of the 1934 strike. Daughter Helen marries Robert Brennan at St. Brigid\'s at 2 o\'clock Saturday.' },
  Freeman: { origin: 'Came north from Virginia, 1919', note: 'Freeman\'s Barber Shop since 1921 (Marcus runs it now). Ruth Freeman is the soloist of the First Congregational choir. Cousin Earl Freeman runs the Blue Lantern club.' },
  Lee: { origin: 'Chinese (Taishan), 1911', note: 'Lee\'s Hand Laundry. Henry Lee, 62. Daughter Grace teaches third grade; son David is in the Navy.' },
  Adler: { origin: 'Jewish, from Vilna, 1905', note: 'Adler & Son, Tailors, since 1906. Isaac Adler, 70, still cuts every suit by hand.' },
  Papadakis: { origin: 'Greek (Chios), 1920', note: 'The Harbor Light Diner. Nick and Eleni Papadakis. Nick\'s father opened the lunch counter in 1924.' },
  Moreau: { origin: 'French-Canadian, 1920s', note: 'Little Susie Moreau turns seven on Saturday. Party at 14 Maple Street, two o\'clock.' },
  Brennan: { origin: 'Irish', note: 'Robert Brennan, 26, linotype operator at the Courier, marries Helen Novak on Saturday.' },
  Kaminski: { origin: 'Polish', note: 'Stan and Carol Kaminski are expecting their first. Stan has worn a groove in the hospital waiting room floor.' },
  Fisk: { origin: 'Old Yankee', note: 'Amos Fisk has kept Whitcomb Point Light since 1921. His wife Opal knits for every baby born in town.' },
  Pemberton: { origin: 'Old Yankee', note: 'Mayor Walter Pemberton, 61. Gives the Centennial address at 5:30.' },
  Pruitt: { origin: 'Old Yankee', note: 'Leonard Pruitt, organist and choirmaster of First Congregational for 30 years. The orchard on Orchard Street was his grandfather\'s.' },
};

export const INSTITUTIONS = [
  { name: 'City Hall', est: 1876, note: 'The "Old Granite Lady". The council chamber served as an influenza ward in 1918.' },
  { name: 'Union Station', est: 1889, note: 'Four trains a day to Boston. The station clock has not been wrong since 1911, says the stationmaster.' },
  { name: 'Whitcomb Point Light', est: 1868, note: 'Fixed white light, visible 14 miles. Kept by Amos Fisk since 1921.' },
  { name: 'Juniper Trust Building', est: 1929, note: '22 stories. WJBY broadcasts from the 21st floor.' },
  { name: 'First Juniper Savings Bank', est: 1871, note: 'Saturday hours 9 to noon.' },
  { name: 'St. Brigid\'s Church', est: 1882, note: 'Granite, with a bell cast in Troy, New York, in 1884.' },
  { name: 'First Congregational Church', est: 1853, note: 'The oldest congregation in town; the present meetinghouse dates from 1871.' },
  { name: 'Carnegie Library', est: 1911, note: 'Librarian: Miss Harriet Mayhew, since 1927.' },
  { name: 'St. Luke\'s Hospital', est: 1920, note: 'Built after the 1918 influenza.' },
  { name: 'Engine Company No. 1', est: 1903, note: 'Home of "Old Faithful", the 1903 steam pumper.' },
  { name: 'The Juniper Bay Courier', est: 1866, note: 'Editor Ada Lowell. The Sunday Centennial edition runs 48 pages.' },
  { name: 'Harbor Canning Co.', est: 1899, note: 'Still the town\'s biggest employer.' },
  { name: 'Harlow\'s Department Store', est: 1878, note: 'Five floors and the only escalator in the county (1949).' },
  { name: 'The Rialto Theatre', est: 1927, note: 'Now showing: "Shane" (7:30) and "Roman Holiday" (2:00 matinee).' },
  { name: 'The Whitcomb Hotel', est: 1896, note: 'Seventy rooms, a palm court, and a bellhop named Earl who has worked there 31 years.' },
  { name: 'Harbor Light Diner', est: 1924, note: 'Open 5 a.m. to midnight. Chowder on Fridays, pie always.' },
];

// Things happening on Centennial Saturday (for the map's "What's On" and the newspaper)
export const TODAY = [
  ['5:00 AM', 'Halloran & Sons Bakery', 'Ovens fired for 400 centennial loaves'],
  ['6:00 AM', 'Pier 3', 'The fishing fleet comes in; Castellano Fish Co. unloads'],
  ['9:00 AM', 'First Juniper Savings Bank', 'Open until noon'],
  ['10:00 AM', 'Founders Square', 'Harbor Days fair opens — stalls, pies, the ring toss'],
  ['11:00 AM', 'Maple Street', 'Engine Co. No. 1 attempts to rescue Mrs. Hatch\'s cat, Admiral'],
  ['2:00 PM', 'St. Brigid\'s Church', 'Wedding of Helen Novak and Robert Brennan'],
  ['2:00 PM', '14 Maple Street', 'Susie Moreau\'s seventh birthday party'],
  ['2:00 PM', 'The Rialto', '"Roman Holiday" matinee'],
  ['4:00 PM', 'First Congregational Church', 'Choir practice for the Centennial service'],
  ['5:30 PM', 'Founders Square', 'Mayor Pemberton\'s Centennial address & time capsule'],
  ['6:00 PM', 'All over town', 'Supper. The Hallorans eat in front of the television.'],
  ['6:30 PM', 'Castellano home', 'Welcome-home supper for Sal Jr.'],
  ['7:30 PM', 'The Rialto', '"Shane"'],
  ['7:30 PM', 'Juniper Bay High School gym', 'Centennial Sock Hop'],
  ['8:00 PM', 'Founders Square', 'Street dance with the Harbor Days Band'],
  ['9:00 PM', 'Over the harbor', 'Centennial fireworks'],
  ['9:00 PM', 'The Blue Lantern', 'Earl Freeman Quartet, late set'],
  ['9:30 PM', 'The Courier', 'Presses roll for the Sunday Centennial edition'],
];
