// Words for Juniper Bay: the raw material sim/dialogue.js uses to give every townsperson a
// history, and the overheard chatter shown in speech bubbles. Pure data — no imports.
// Keep consistent with city/lore.js, sim/roster.js and the plaques the building generators write.
// Templates use {placeholders}; see fill() in dialogue.js.

// ---------------------------------------------------------------- heritage
// who a family is, where they came from, when, and what they brought.
export const HERITAGE = {
  irish: {
    label: 'Irish', church: "St. Brigid's", years: [1878, 1912],
    places: ['County Clare', 'County Cork', 'County Kerry', 'County Galway', 'County Mayo', 'County Donegal', 'County Waterford'],
    came: [
      '{Who} came over from {place} in {year} to lay track for the Boston & Juniper Bay, and stayed to work the wharves.',
      '{Who} came from {place} in {year} with a tin trunk and a letter from the parish priest.',
      '{Who} landed in Boston from {place} in {year} and walked the last forty miles, because the train cost money.',
      '{Who} came out of {place} in {year} and went straight to work on the cannery wharf.',
    ],
    keepsakes: ["a Claddagh ring from {place}", "a St. Brigid's cross woven out of rushes", "a blackthorn stick from {place}", "the brass kettle that came over in the steerage", "a rosary blessed at Knock", "a photograph of a thatched cottage nobody's seen in seventy years", "a fiddle nobody in the family can play anymore"],
    elder: ['Nana', 'Granny', 'Grandda', 'Gran'],
    words: ["God rest him.", "Sure, and why not.", "Please God."],
  },
  italian: {
    label: 'Italian', church: "St. Brigid's", years: [1894, 1914],
    places: ['Sciacca, in Sicily', 'Palermo', 'Naples', 'Genoa', 'Avellino', 'the Abruzzi', 'Calabria', 'Bari'],
    came: [
      '{Who} came from {place} in {year} and went out on the Castellano boats the first week.',
      '{Who} came over from {place} in {year} with a mandolin and eleven dollars.',
      '{Who} sailed from {place} in {year} and cut ice on the harbor the first winter, for want of anything else.',
      '{Who} came from {place} in {year}, followed a cousin here, and never followed anybody again.',
    ],
    keepsakes: ["a statue of San Rocco that came over wrapped in a shawl", "Nonna's pasta board, worn thin in the middle", "a mandolin from {place}", "a coffee pot from {place} that nobody's allowed to wash with soap", "a picture of the Madonna del Soccorso", "Nonno's fishing knife"],
    elder: ['Nonna', 'Nonno'],
    words: ["Madonna.", "Salute.", "Mangia."],
  },
  polish: {
    label: 'Polish', church: "St. Brigid's", years: [1904, 1914],
    places: ['near Kraków', 'Galicia', 'a village outside Poznań', 'near Tarnów', 'near Białystok', 'the hills south of Kraków'],
    came: [
      '{Who} came from {place} in {year} to work the cannery, with the Novaks and the Kowalskis.',
      '{Who} came from {place} in {year} with a feather bed, a crucifix and a promise of work on the sardine line.',
      '{Who} came over from {place} in {year} and packed fish at Harbor Canning for thirty-one years.',
    ],
    keepsakes: ["a Black Madonna of Częstochowa over the bed", "Babcia's feather bed from {place}", "a painted Easter egg from 1908, still whole", "a wooden spoon from {place} that makes the pierogi taste right", "a lace tablecloth for Wigilia"],
    elder: ['Babcia', 'Dziadek'],
    words: ["Sto lat!", "Na zdrowie."],
  },
  frenchcanadian: {
    label: 'French-Canadian', church: "St. Brigid's", years: [1916, 1932],
    places: ['Trois-Rivières', 'Sherbrooke', 'Saint-Hyacinthe', 'the Beauce', 'Rivière-du-Loup', 'Chicoutimi'],
    came: [
      '{Who} came down from {place} in {year} for the mills in Lowell, and then here, for the sea air.',
      '{Who} came down from {place} in {year} with six children and a sewing machine.',
      '{Who} came down from {place} in {year} for the mills, and ended up building boats at Bayside instead.',
    ],
    keepsakes: ["Mémère's tourtière tin", "a sash, a ceinture fléchée, from {place}", "a crucifix from Sainte-Anne-de-Beaupré", "a fiddle for the réveillon", "a book of prayers in French with every birthday written in the back"],
    elder: ['Mémère', 'Pépère'],
    words: ["Mon Dieu.", "Bonne fête."],
  },
  portuguese: {
    label: 'Azorean', church: "St. Brigid's", years: [1891, 1925],
    places: ['São Miguel', 'Faial', 'Pico', 'Terceira', 'Flores', 'São Jorge'],
    came: [
      '{Who} came from {place} in the Azores in {year} and fished out of Pier 3 the next morning.',
      '{Who} came from {place} in {year} on a whaling bark and walked off it into Juniper Bay.',
      '{Who} came from {place} in {year}, when the first Azorean families were settling along the south wharves.',
    ],
    keepsakes: ["a painted tile of the Holy Ghost from {place}", "Avó's black shawl", "a silver crown from the Holy Ghost feast", "a picture of the harbor at {place}", "a fado record, played only on Sundays"],
    elder: ['Avó', 'Avô'],
    words: ["Saúde.", "Graças a Deus."],
  },
  capeverdean: {
    label: 'Cape Verdean', church: "St. Brigid's", years: [1900, 1925],
    places: ['Brava', 'Fogo', 'São Nicolau', 'Santo Antão'],
    came: [
      '{Who} came from {place} in the Cape Verde Islands in {year} on a whaling packet, picked cranberries on the Cape, and came up to fish.',
      '{Who} came over from {place} in {year} and signed on a Juniper Bay schooner the week the ship came in.',
    ],
    keepsakes: ["a morna record from {place}", "Grandmother's cachupa pot", "a carved whale's tooth from the packet ship", "a letter from {place} nobody can bear to throw away"],
    elder: ['Nha Nha', 'Grandpa'],
    words: ["Saúde."],
  },
  jewish: {
    label: 'Jewish', church: 'the synagogue on the Salem road', years: [1900, 1914],
    places: ['Vilna', 'Minsk', 'Kovno', 'Odessa', 'Białystok', 'Kishinev', 'a village outside Pinsk'],
    came: [
      '{Who} came from {place} in {year} with a peddler\'s pack and sold needles and thread door to door.',
      '{Who} came from {place} in {year}, a tailor, and went to work for Isaac Adler the first week.',
      '{Who} left {place} in {year}, a step ahead of the pogroms, and never once complained about a New England winter.',
    ],
    keepsakes: ["brass Sabbath candlesticks from {place}", "a silver kiddush cup that crossed the ocean in a stocking", "a feather comforter from {place}", "a prayer book with every birth and death written in the back"],
    elder: ['Bubbe', 'Zayde'],
    words: ["Mazel tov.", "L'chaim."],
  },
  chinese: {
    label: 'Chinese', church: 'First Congregational', years: [1905, 1925],
    places: ['Taishan', 'Kaiping', "Boston's Chinatown", 'Canton'],
    came: [
      '{Who} came from {place} in {year}, when the law made it very hard for a Chinese man to come at all, and came anyway.',
      '{Who} came up from {place} in {year} to work in Lee Wing\'s laundry, and saved for eleven years for a place of our own.',
    ],
    keepsakes: ["Grandfather's abacus", "a jade bracelet from {place}", "a tin box of letters from {place}", "a scroll with the family's names going back twelve generations"],
    elder: ['Nai Nai', 'Yeh Yeh'],
    words: [],
  },
  greek: {
    label: 'Greek', church: 'the Greek church in Lynn', years: [1908, 1924],
    places: ['Chios', 'Sparta', 'Crete', 'Mytilene', 'the Peloponnese', 'Kalymnos'],
    came: [
      '{Who} came from {place} in {year} and opened a fruit stand before anybody in the family could say “apple” in English.',
      '{Who} came from {place} in {year} and worked the candy kitchens in Boston before coming up the coast.',
      '{Who} came from {place} in {year}, where the family dove for sponges, and ended up cutting fish at Pier 3 instead, which was drier, at least.',
    ],
    keepsakes: ["an icon of St. Nicholas, patron of sailors", "a string of worry beads from {place}", "Yiayia's copper briki for the coffee", "a photograph of a white church above a blue harbor at {place}"],
    elder: ['Yiayia', 'Pappou'],
    words: ["Yamas!"],
  },
  scandinavian: {
    label: 'Scandinavian', church: 'First Congregational', years: [1885, 1914],
    places: ['Göteborg', 'Stavanger', 'Bergen', 'Malmö', 'Kristiansand'],
    came: [
      '{Who} came from {place} in {year} as a sailor, jumped ship in Boston, and walked up the coast until the harbor looked right.',
      '{Who} came from {place} in {year} and built boats at Bayside for forty years.',
    ],
    keepsakes: ["a painted wooden horse from {place}", "a ship in a bottle, built in the fo'c'sle on the way over", "a Bible in Swedish nobody can read now", "Grandfather's sea chest from {place}"],
    elder: ['Mormor', 'Farfar'],
    words: ['Skål!'],
  },
  black: {
    label: 'Black', church: 'First Congregational', years: [1916, 1930],
    places: ['Virginia', 'North Carolina', 'South Carolina', 'Georgia', 'Maryland', 'Tidewater Virginia'],
    came: [
      '{Who} came north from {place} in {year}, on the train with a cardboard suitcase, like so many did.',
      '{Who} came up from {place} in {year} because the shipyards were hiring and the South wasn\'t anything to stay for.',
      '{Who} came north from {place} in {year} and never went back, except for funerals.',
      "We're no newcomers — the family's been in Juniper Bay since 1866, same as the Washingtons. Longer than plenty who call themselves old families.",
    ],
    keepsakes: ["the family Bible with names written back to 1840", "Grandmother's quilt from {place}", "a photograph of Great-grandfather in a Union uniform", "a cast-iron skillet older than the Custom House"],
    elder: ['Big Mama', 'Granddaddy'],
    words: [],
  },
  vietnamese: {
    label: 'Vietnamese', church: "St. Brigid's", years: [1927, 1932],
    places: ['Haiphong', 'Saigon', 'Hanoi'],
    came: [
      '{Who} came as a cook on a French freighter out of {place} in {year} and stayed when she sailed, which surprised everybody, the captain most of all.',
    ],
    keepsakes: ["a lacquer box from {place}", "a photograph of {place} harbor", "a porcelain bowl that came over in a sea bag"],
    elder: ['Bà', 'Ông'],
    words: [],
  },
  yankee: {
    label: 'Yankee', church: 'First Congregational', years: [1853, 1895],
    places: ['Cape Cod', 'Maine', 'New Hampshire', 'Salem', 'Nantucket', 'Vermont', 'the North Shore'],
    came: [
      'We\'ve been in Juniper Bay since the charter — the family was among the two hundred and twelve souls of 1853, and we don\'t let anybody forget it.',
      '{Who} came up from {place} in {year} to work in the Custom House and married a Juniper Bay girl.',
      '{Who} came down from {place} in {year} for the cannery office and never went home.',
      'The family\'s been on this coast since before anybody wrote it down. {Who} came to Juniper Bay from {place} in {year}.',
    ],
    keepsakes: ["a sea chest from the China trade", "a whale-oil lamp from the first town hall steps", "a sampler stitched in 1840 by a girl nobody remembers", "a brass spyglass", "a Springfield musket from 1861 over the mantel", "a scrimshaw whale's tooth", "Great-grandmother's pewter"],
    elder: ['Gram', 'Grampa'],
    words: ['Ayuh.'],
  },
};

// Surnames from people/appearance.js (and a few more) → heritage.
export const SURNAME_HERITAGE = {
  Halloran: 'irish', Brennan: 'irish', Sullivan: 'irish', Tobin: 'irish', Callahan: 'irish', Duffy: 'irish', Rourke: 'irish', Garrity: 'irish', Flanagan: 'irish', Doyle: 'irish', Kearney: 'irish', Dolan: 'irish', Coffey: 'irish', Keane: 'irish',
  Castellano: 'italian', Russo: 'italian', Bianchi: 'italian', DeLuca: 'italian', Marchetti: 'italian',
  Novak: 'polish', Kowalski: 'polish', Kaminski: 'polish', Wojcik: 'polish', Wrobel: 'polish', Kowalczyk: 'polish',
  Moreau: 'frenchcanadian', Beaumont: 'frenchcanadian', Tremblay: 'frenchcanadian', Gagnon: 'frenchcanadian',
  Silva: 'portuguese', Medeiros: 'portuguese', Costa: 'portuguese', Furtado: 'portuguese',
  Adler: 'jewish', Goldberg: 'jewish', Weiss: 'jewish', Stein: 'jewish', Kaplan: 'jewish', Cohen: 'jewish',
  Lee: 'chinese', Chen: 'chinese', Wong: 'chinese',
  Papadakis: 'greek', Kouris: 'greek',
  Lindqvist: 'scandinavian', Olsen: 'scandinavian',
  Nguyen: 'vietnamese',
  // Freeman / Jackson / Washington / Coleman / Porter are Yankee names too; dialogue.js makes them
  // (or anyone) Black when the whole household is.
};
export const MAYBE_BLACK = new Set(['Freeman', 'Jackson', 'Washington', 'Coleman', 'Porter']);
export const FOUNDING_NAMES = new Set(['Whitcomb', 'Pruitt', 'Dunmore', 'Hatch', 'Fisk', 'Pike', 'Mayhew', 'Crowell', 'Beal', 'Carver', 'Ashby']);

// ---------------------------------------------------------------- names for people who aren't on stage
export const OFFSTAGE = {
  male: ['Harold', 'Walter', 'Frank', 'Albert', 'George', 'Joseph', 'Edward', 'Raymond', 'Charles', 'Arthur', 'Francis', 'Leo', 'Herbert', 'Ernest', 'Tom', 'Jimmy', 'Bill', 'Eddie', 'Paul', 'Richard', 'Donald', 'Jack'],
  female: ['Mary', 'Margaret', 'Dorothy', 'Helen', 'Ruth', 'Alice', 'Florence', 'Rose', 'Anna', 'Catherine', 'Jean', 'Louise', 'Betty', 'Joan', 'Nancy', 'Eleanor'],
  away: ['Hartford', 'Worcester', 'Springfield', 'Providence', 'Portland', 'Lynn', 'Brockton', 'New Haven', 'Albany', 'Chicago', 'California', 'Fort Devens', 'Norfolk, with the Navy', 'Germany, with the Army', 'Korea, still, with the 7th Division'],
  towns: ['Salem', 'Beverly', 'Gloucester', 'Rockport', 'Ipswich', 'Newburyport', 'Marblehead', 'Lynn', 'Peabody', 'Danvers', 'Manchester', 'Essex'],
};

// ---------------------------------------------------------------- what the elders remember
// each: [minAge, maxAge, line, year of the event]. Lines are first-person; only offered to people who were in town by then.
export const MEMORIES = [
  [70, 120, 'I was a child when they unveiled the bronze soldier in the square, 1889. The whole town sang “Tenting Tonight” and my grandmother cried for her brother.', 1889],
  [69, 120, 'I remember when Union Station opened in \'89 — the great arched shed. We thought it was a cathedral. We thought the trains were God.', 1889],
  [66, 120, 'The Great Gale of \'98, the Portland Gale — I was a young one. The Liberty Elm on the City Hall lawn came through it. So did we, mostly.', 1898],
  [62, 120, 'I was grown when the Great Fire went through Market Street in 1902. We passed buckets from the harbor for six hours. Not one soul lost. Three blocks, but not one soul.', 1902],
  [55, 70, 'I was a child the day of the Great Fire. Mother held me up at the window. You could have read a newspaper at midnight by the glow.', 1902],
  [56, 120, 'For the semi-centennial in 1903 they put up the Whitcomb Fountain, and old Mr. Pruitt\'s band played a quickstep he wrote. Fifty years. Now here we are again.', 1903],
  [54, 120, 'The day the trolley came down Lantern Avenue in 1906, everybody rode for free. I went round nine times and got sick on the ninth.', 1906],
  [50, 120, 'I was there when the Carnegie Library opened in 1911. Every family on Hillcrest sent a box of books. We thought we were in Boston.', 1911],
  [44, 120, 'In 1918 the influenza came. They made the council chamber at City Hall into a ward. We tied a white rag on the door when somebody in the house had it. So many rags that fall.', 1918],
  [44, 120, 'Two hundred and twelve of our boys went to France in 1917. Nine didn\'t come back. There\'s an oak in Juniper Park for each of them. I know which one is which.', 1917],
  [40, 120, 'I remember Armistice Day, 1918. They announced it from the City Hall portico while the influenza ward was still open upstairs. We cheered and we whispered at the same time.', 1918],
  [36, 120, 'I remember when WJBY went on the air in 1928, from a closet over the Savings Bank. Father held the aerial wire for an hour so Mother could hear the church service.', 1928],
  [36, 120, 'They finished the Trust Building in October of \'29, tallest thing on the coast. Three weeks later, the Crash. The Trust never missed a payroll, I\'ll give old Josiah Crane that.', 1929],
  [32, 120, 'In \'32 Halloran\'s sold day-old bread for a penny, and whatever didn\'t sell went out the back door to anybody who knocked. We knocked. Everybody knocked.', 1932],
  [30, 120, 'Nineteen days in July of \'34 they stood on the City Hall steps. Casimir Novak spoke, and we won a nickel an hour. Mrs. Novak made sandwiches for four hundred.', 1934],
  [30, 120, 'In \'34 Nick Papadakis\'s father poured free coffee for the strikers every morning. The cannery never forgave him. We never forgot. I still eat at the Harbor Light because of it.', 1934],
  [25, 120, 'The WPA rebuilt the seawall in \'36 — two hundred and twelve men of this town who\'d have had no work that winter otherwise. It held in \'38. That\'s all you need to know about it.', 1936],
  [21, 120, 'The hurricane, September 21st, 1938. Six feet of water on Harbor Street. Pier 3 went out to sea with three good men. Go and look at the high-water line on the buildings and then look at the harbor on a calm day.', 1938],
  [21, 120, 'After the \'38 blow the elms on Elm Street were lying across the road like matchsticks. You couldn\'t see Maple Street for the branches.', 1938],
  [19, 30, 'In \'39, after the hurricane, our class planted maples on Elm Street to replace the elms. Mine\'s the fifth from the corner. I go and look at it sometimes when nobody\'s watching.', 1939],
  [22, 120, 'V-J Day we all ended up in Founders Square. The bells at St. Brigid\'s rang for an hour, till the rope broke. Somebody climbed the bronze soldier with a flag. I won\'t say who. Nick Papadakis.', 1945],
  [17, 30, 'In the war we collected scrap on Saturdays — pots, pans, a whole iron fence off Hillcrest Avenue. Mrs. Hatch gave us her husband\'s spare anchor. We pulled it in a wagon.', 1942],
  [26, 60, 'They built wooden minesweepers at Bayside all through the war, forty-one of them. You could hear the hammers from Maple Street till midnight.', 1942],
  [14, 26, 'V-J Day I was just a kid. Somebody lifted me up on a lamppost on the square and I could see the whole town, every single person, shouting. I\'ve never seen it like that since. Until today, maybe.', 1945],
];

// ---------------------------------------------------------------- the young
export const TEEN_LINES = [
  'The sock hop\'s at half past seven. Shoes off at the door — Mr. Coleman\'s orders. He waxed the floor till two in the morning.',
  'Did you hear “Rags to Riches” on the radio? Tony Bennett. It\'s the most.',
  'F|Eddie Fisher is dreamy. My mother says he looks like a bank clerk. My mother doesn\'t know anything.',
  'M|My sister thinks Eddie Fisher is dreamy. He sings like a man who\'s never had to carry a sardine crate. I\'m just saying.',
  'Mr. Bishop\'s lending every record in the store for the sock hop. If anybody scratches “Vaya con Dios” he\'ll have us all arrested.',
  'Ted Williams is back from Korea and hitting like he never left. He flew jets over there! Real jets!',
  'The Braves moved to Milwaukee. Milwaukee! My dad hasn\'t forgiven them. He says he\'s a Red Sox man now, out of spite.',
  'We play Gloucester Friday. If we lose, Coach says we\'re running laps to the lighthouse.',
  'I saw “From Here to Eternity” in Salem. My mother thinks I saw “Lili.” Don\'t tell.',
  '“House of Wax” in 3-D! They gave you cardboard glasses. I kept mine. I wear them to breakfast.',
  'Buddy Keene sings Eddie Fisher at the soda fountain at Mayhew\'s. The root beer floats taste better when he\'s singing. Don\'t ask me why.',
  'My big brother\'s in Korea with the Army. The war\'s over, but they haven\'t sent him home yet. Ma saves him a plate every Sunday anyway.',
  'Did you see Marciano on the radio — well, hear him? Knocked out LaStarza Thursday night. A Brockton boy! Heavyweight champion of the world!',
  'M|I\'m saving up for a Schwinn. Nine dollars to go. I set pins at Harbor Lanes Friday nights for a nickel a line.',
  'The Coronation was on the newsreel at the Rialto in June. The Queen\'s only twenty-seven. Mary Brennan says she wants to be a queen. I told her there\'s already one in Juniper Bay: Mrs. Pemberton.',
  'Everybody signs the Centennial Book at the Historical Society table. I signed mine with a little lighthouse. In 2053 they\'ll think I was an artist.',
  'F|I\'m going to be a stewardess and fly to Paris. Or a nurse. Or a stewardess who\'s a nurse.',
  'Peggy Halloran says she\'s going to the sock hop with Joanie. Everybody knows what that means.',
  'Duck and cover drill Thursday at ten. We all got under our desks and Walter Novak fell asleep under his.',
];
export const KID_LINES = [
  'I\'m gonna see the fireworks! I\'m staying up till NINE.',
  'Wanna play? We\'re playing Lone Ranger. I\'m Tonto. Tonto\'s smarter.',
  'I got a candy apple at the fair! It was a nickel! My teeth are stuck!',
  'Didja see the fire engine? They put the big ladder up the tree for Mrs. Hatch\'s cat!',
  'Mr. Draper\'s got the train going in the window. It goes through a tunnel and a mountain and EVERYTHING.',
  'Mr. Kouris gave me a jawbreaker. It\'s bigger than my mouth. I\'m working on it.',
  'I can say the whole Pledge of Allegiance. Want to hear? ...Okay, maybe later.',
  'Skippy Mercer can run faster than a car. Well, faster than Mr. Finch\'s trolley. Well, almost.',
  'We had a duck-and-cover drill Thursday. You get under your desk and hold your neck. I don\'t know why the neck.',
  'I traded two Yogi Berras for a Mel Parnell. Tommy Halloran says I got robbed. Tommy Halloran says that about everything.',
  'Howdy Doody\'s on the Hallorans\' television. We all go over and sit on the rug. Grandma Halloran gives us a look.',
  'I drew a picture for the time capsule! It\'s the lighthouse. And a whale. There\'s no whale really, but there should be.',
  'Mom says no swimming at the beach in August, because of polio. It\'s September now. It\'s too cold anyway. Everything\'s always something.',
  'When I grow up I\'m gonna be a fireman like Captain Brennan. Or a cowboy. Or both.',
  'M|Ma says if I get my good pants dirty before the fireworks she\'ll skin me. These are my good pants.',
  'F|Ma says if I get my party dress dirty before the fireworks I\'m going straight to bed. I\'m being VERY careful.',
  'There\'s a Space Cadet show on television. Tom Corbett. I\'m going to the moon when I\'m big. Or Boston.',
];
export const TODDLER_LINES = [
  'Fire truck! Fire truck!', 'Kitty up the tree!', 'I\'m four. Almost.', 'Want a cookie.', 'Boom! Boom! Fireworks go boom!', 'That\'s my mommy.', 'Balloon!', 'Birdie! Birdie!',
];

// ---------------------------------------------------------------- what people think
export const OPINIONS = [
  // television
  'Television! The Hallorans have one on Church Street and now nobody on the block will go to bed. Mark my words, it\'ll be the end of conversation.',
  'We\'re getting a television at Christmas. Vic DeLuca says a dollar a week. I said over my dead body. So — probably Christmas.',
  'I watched Milton Berle at the Hallorans\'. I don\'t see what the fuss is about. I watched him for two hours to make sure.',
  'A television is a radio you have to look at. What\'s the use of that? You can\'t shell peas and look.',
  // the supermarket
  'Have you been to the new supermarket in Gloucester? You push a wire cart and nobody says good morning. The prices are good, though. I hate that the prices are good.',
  'The supermarket in Gloucester has frozen peas, frozen fish, frozen everything. My mother would\'ve called it a morgue.',
  'I\'ll shop at Kowalski\'s till they carry me out. Ted knows I like the heel of the rye. Does a supermarket know that?',
  // the cannery
  'Birds Eye makes fish sticks now — frozen, in a box. That\'s the end of the sardine tin, if you ask me. And then what happens to the cannery? Half this town packs fish.',
  'The cannery\'s been “dying” since 1932. It\'s still the biggest employer in town. It\'ll outlast us all, smell and all.',
  'They say the Norwegians and the Portuguese can pack sardines cheaper than we can. Let them try to pack them better.',
  // the trolley
  'They want to put buses on Lantern Avenue instead of the trolley. Buses! A bus is just a truck that\'s given up.',
  'Buses would be better, honestly. The trolley can\'t go round a parked car. But don\'t tell Lloyd Finch I said so.',
  'The Mayor says the trolley stays as long as he\'s mayor. That\'s either a promise or a prediction.',
  // roads and the future
  'Route 128\'s open all the way round Boston now. People will live up here and work down there. I don\'t know if that\'s progress or just traffic.',
  'They\'re building little Cape Cod houses out past Orchard Street, G.I. terms, eight thousand nine hundred. Every young couple in town is looking, and counting on their fingers.',
  'Forty mercury-vapor lamps on Harbor Street by spring, thirty-eight thousand dollars. The old arc lamps were good enough for the Great Fire. Well — maybe that\'s not a recommendation.',
  // politics and the world
  'Ike\'s all right. He ended the war in Korea, didn\'t he? Or anyway it ended while he was there. That\'s all I ask of a president.',
  'Did you see the pictures of the Kennedy wedding in Newport? Two weeks ago today. An Irish Catholic boy from Boston, a Senator. My grandmother would\'ve fainted.',
  'The Russians have the hydrogen bomb now too. They tested it in August. And we do duck-and-cover drills under school desks. I\'ll say an extra prayer, that\'s what I\'ll do.',
  'I turned off Senator McCarthy on the radio. This town sent boys to two wars so a person could turn off whoever they like.',
  'They say a doctor in Pittsburgh is close to a vaccine for polio. Please God. Every August I keep the children home from the beach and pray.',
  // prices
  'Ninety-three cents for a pound of coffee at Kowalski\'s! When I was young you could buy a whole Sunday dinner for ninety-three cents.',
  'Bread\'s eighteen cents. Halloran\'s bread, mind you, so it\'s worth it. But eighteen cents!',
  // baseball
  'Red Sox are fourth. Again. Williams is back, though. Next year. It\'s always next year in this town.',
  'The Yankees have won the pennant five years running. It isn\'t baseball anymore, it\'s bookkeeping.',
  // the town
  'The Mayor\'s speech was eleven pages. Mrs. Pemberton cut it to six. She should run for mayor. Half the town already thinks she does.',
  'A time capsule! What do you suppose they\'ll make of us? I hope they know we meant well.',
  'Harlow\'s escalator. I\'ve ridden it twice. The second time on purpose.',
  'The young people today — sock hops, jitterbug, Eddie Fisher. Well. We had the turkey trot and our parents thought the world was ending then too.',
  'Fireworks from a barge! Mrs. Pemberton says don\'t ask what it cost. I asked. Don\'t ask.',
];

// ---------------------------------------------------------------- the Centennial Book (every signature goes in the capsule)
export const CENTENNIAL = [
  'I signed the Centennial Book at the Historical Society table. Under my name I wrote: “We were here. It was a good place.” What else is there?',
  'Every signature from the fair goes in the time capsule. I signed for the whole family, even the dog. In 2053 somebody\'s going to wonder who “Buster” was.',
  'I wrote in the Centennial Book: “Dear 2053 — keep the lighthouse lit.” That\'s all. Amos Fisk would approve.',
  'Our {child} wrote a letter for the capsule at school. It asks if they still have pie at the diner. Good question.',
  'Under my name in the Centennial Book I put the price of a haddock and the price of a loaf. Let them laugh. Then let them cry.',
  'They\'re putting a telephone directory in the capsule. Four thousand two hundred and twelve listings. We\'re in it. We\'ll be in the ground under the Soldiers\' Monument for a hundred years. Ha!',
  'I wrote in the Centennial Book: “Be kind to each other.” Then I felt silly, so I added “and fix the potholes on Canal Street.”',
  'Half past five, the Mayor seals the capsule. To be opened September 26th, 2053. I\'ll be a hundred and something. I intend to be there.',
  'The copper box for the time capsule was made by the apprentices at Bayside Boat Works. If it leaks, we\'ll know who to blame. In 2053.',
  'I signed the Centennial Book and then I stood there reading the other names. Half the town. Everybody I ever knew. It gave me a turn.',
];

// ---------------------------------------------------------------- talk of the town (about: surnames or full names to skip for relatives)
export const GOSSIP = [
  { about: ['Halloran', 'Kaminski'], text: 'Don\'t repeat this, but Peggy Halloran is going to the sock hop “with Joanie.” Joanie AND the Kaminski boy, if you believe Hazel Oakes. And everybody believes Hazel Oakes.' },
  { about: ['Novak', 'Ashby', 'Mayhew'], text: 'They say Walter Novak and the Reverend\'s daughter have been at the same table at the library every afternoon since Labor Day. Miss Mayhew won\'t say a word. That\'s how you know it\'s true.' },
  { about: ['Castellano', 'Flanagan'], text: 'Dottie Flanagan wrote Sal Castellano Jr. every single week he was in Korea. Fifty-eight letters! And he hasn\'t asked her to the street dance yet. Men.' },
  { about: ['Ferris', 'Sayer', 'Oakes'], text: 'Bill Ferris from the radio asked Evelyn Sayer to the street dance. On the telephone. Hazel Oakes was on the party line. So now the whole town knows, and Evelyn\'s pretending not to.' },
  { about: ['Quimby', 'Halloran', 'Garrity'], text: 'Loretta Quimby pulled her pie out of the contest when she saw Father Garrity was judging. Says it\'s 1949 all over again. Irene Halloran is being very gracious about it. Very loudly gracious.' },
  { about: ['Pruitt'], text: 'Leonard Pruitt and his brother\'s widow haven\'t spoken since 1926. Over an orchard! And she sits in the back pew every single Sunday to hear him play. Figure that out.' },
  { about: ['Bower', 'Whitcomb'], text: 'The Bower sisters aren\'t speaking. Something about a white rose and a sprig of juniper for the time capsule. Florists! They\'ll make up by Tuesday. They always do.' },
  { about: ['Novak', 'Brennan'], text: 'Stella Novak told Nora Brennan: no yellow in the corsage. Nora Brennan wore yellow anyway. Tucked under the fern. Ivy Bower did it on purpose, if you ask me.' },
  { about: ['Garrity', 'Halloran', 'Castellano'], text: 'Tom Garrity still swears the Halloran boy was out at home last Saturday. His own brother the priest says safe. That\'s a family with a split verdict.' },
  { about: ['Hatch', 'Brennan'], text: 'Mrs. Hatch\'s cat was up the maple again this morning. Five times since Easter! Joe Brennan says next time he\'s sending her a bill. She says she\'ll send him a pie. Stalemate.' },
  { about: ['Pemberton'], text: 'The Mayor\'s speech was eleven pages. Mrs. Pemberton cut it to six with a green pencil. I heard the part about the water department is still in there, hiding.' },
  { about: ['Papadakis', 'Tobey'], text: 'Eleni Papadakis never charges Lonnie Tobey for his breakfast. She says she forgets. Eleni Papadakis has never forgotten an order in fifteen years.' },
  { about: ['Ellsworth', 'Tobey'], text: 'Old Cyrus Ellsworth has had Lonnie Tobey\'s great-grandfather\'s watch in his safe since 1932 and won\'t sell it. Tight as a drum, Cyrus. Except when he isn\'t.' },
  { about: ['Kaminski'], text: 'Stan Kaminski has been pacing St. Luke\'s since midnight. They say he\'s asked the nurses for news every four minutes. Dr. Pike finally told him to go smoke a pipe. He doesn\'t own a pipe.' },
  { about: ['Kowalski'], text: 'You know Ted Kowalski got a Silver Star at Bastogne? You\'ll never hear it from him. His mother found it in his drawer. She\'s never said a word to him either. Polish families.' },
  { about: ['Weiss', 'Halloran'], text: 'Jacob Weiss has put aside that charm bracelet in his window for Peggy Halloran. Fourteen dollars. She doesn\'t know. Don\'t you dare tell her.' },
  { about: ['Wrobel', 'Coleman'], text: 'Rufus Coleman has got old Stan Wrobel from the cannery to stand at the door of the sock hop. Nobody\'s getting a flask past those two. Nobody.' },
  { about: ['Lindqvist', 'Castellano'], text: 'Otto Lindqvist pulled the train whistle himself on Tuesday when the Castellano boy came home on the 4:52. Otto Lindqvist! He\'s never done anything against regulations in his life.' },
  { about: ['Keene', 'Oakes'], text: 'Shirley Oakes goes into Mayhew\'s for a lime rickey three times a week, and Buddy Keene hasn\'t noticed. The whole town has noticed. Buddy hasn\'t.' },
  { about: ['Draper'], text: 'Old Mr. Draper offered to carve a dory for the time capsule and the committee said no room. He\'s taken it very hard. He\'s told everybody who\'s come in the shop. Twice.' },
  { about: ['Papadakis'], text: 'Nick Papadakis is judging the pie contest and his own wife entered a Dutch apple. If he votes for her it\'s a scandal. If he doesn\'t, he\'s sleeping in the diner.' },
  { about: ['Pike', 'Mayhew'], text: 'Josephine Pike and Harriet Mayhew have been rivals since 1927 — books for sale, books for free. They have lunch every Thursday. Nobody understands it. Everybody\'s jealous.' },
  { about: ['Thorne', 'Fairweather'], text: 'Mr. Thorne says the trolley started in June of 1906. Miss Fairweather says May, and she was on it. He\'s got the documents. She\'s got the memory. My money\'s on Miss Fairweather.' },
  { about: ['Gould', 'Novak'], text: 'Stella Novak changed her mind about her hat four times. Madame Gould finally wrote FINAL in the appointment book. In ink.' },
  { about: ['DeLuca', 'Kowalski'], text: 'Vic DeLuca tells his war story at one end of the Signal Lamp bar and Ted Kowalski sits at the other end and never says a word. Between them, Mike Flanagan says, one normal veteran.' },
  { about: ['Freeman'], text: 'Earl Freeman says his cousin\'s boy Sammy is going to play horn at the Blue Lantern someday. Marcus says finish school first. Earl agrees with him, which surprised everybody.' },
  { about: ['Beal'], text: 'Somebody took the brass key to the Records Vault at City Hall. Miss Lydia Beal put a notice on the board: return it, NO QUESTIONS. Nobody believes the no questions part.' },
  { about: ['Pruitt', 'Castellano'], text: 'Mrs. Pruitt is still holding Room 3C for the Castellano boy through October, though he\'s home and won\'t need it. Paid up, she says. That woman\'s got a heart under all that starch.' },
  { about: ['Fisk', 'Flanagan'], text: 'Amos Fisk walks into the Signal Lamp every Saturday at four for exactly one beer, and to check Mike Flanagan\'s been polishing the old lighthouse lamp. Thirty years. One beer.' },
  { about: ['Tremblay'], text: 'Lucien Tremblay had twins a week ago! John and James. Armand walked around the furniture store all day telling customers. Sold four sofas out of pure joy.' },
  { about: ['Russo'], text: 'Old Vincenzo Russo\'s a great-grandfather since the second. Dominic Paul. He handed out sausage to the whole of Market Street. Six blue ribbons and now this.' },
  { about: ['Castellano'], text: 'Carmela and Rosa Castellano are both making cannoli for tonight\'s supper. Two trays. One family. We\'ll see which tray comes home empty.' },
  { about: ['Oakes'], text: 'Chester Oakes has carried the mail for twenty-six years and never once said what\'s in it. His wife Hazel knows anyway. Nobody knows how.' },
  { about: ['Kaminski'], text: 'Did you hear? Carol Kaminski went into St. Luke\'s last night. Stan left a note on the kitchen table in capital letters and forgot his hat. Mrs. Kowalski next door found it.' },
  { about: ['Adler'], text: 'Esther Adler has been after Isaac to close on Saturdays for forty-seven years. He says he\'s almost ready. He\'s been almost ready since 1906.' },
];

// ---------------------------------------------------------------- off-roster work (for adults with no job on the map)
// weekday jobs and trades that don't have a building of their own. {m} = men, {f} = women.
export const OFF_JOBS = {
  m: [
    ['packs sardines on Line 2 at Harbor Canning, weekdays', 'Forty tins a minute on the line, weekdays. Saturdays I dream about sardines.'],
    ['drives a truck for Bayside Ice & Coal', 'Ice in summer, coal in winter, and in between I drive whatever they give me. Coal\'s coming up. You can smell October.'],
    ['is a lineman for the telephone company, same crew as Stan Kaminski', 'Stan Kaminski\'s on my crew. Poor devil\'s been at St. Luke\'s since midnight. I\'d rather climb a pole in an ice storm.'],
    ['works on the railroad section gang', 'I keep the rails straight from here to Beverly. Otto Lindqvist inspects them with his eyes like a bird. Never found a thing out of place yet. On my stretch.'],
    ['fishes on the Castellano boats', 'Out at three, in by six. We had a good trip this morning. You\'ll be eating it tonight, if you\'re smart.'],
    ['is a carpenter, mostly roofs', 'Half the roofs on Maple Street I\'ve had my hands on. Since \'38 I nail everything twice.'],
    ['works at the shoe factory in Lynn, driving down every day with three other fellows', 'Four of us in a \'41 Plymouth to Lynn and back every day. We\'ve told every story we know twice. Now we just sing.'],
    ['clerks at the Harbor Insurance Building, weekdays', 'Insurance. I sit at a desk and imagine disasters for a living. Then I go home and fix the gutters.'],
    ['works the boiler room at St. Luke\'s', 'I keep the heat on at St. Luke\'s. The nurses say I\'m the most important man in the building. The doctors don\'t say.'],
    ['is a plumber, and proud of it', 'Plumber. When I was a boy half this town had a privy out back. Now look. That\'s progress you can sit on.'],
    ['works for the Board of Public Works, fixing the streets', 'Public Works. Mr. Crowell has me on the potholes on Canal Street. Twelve years. They\'re very loyal potholes.'],
    ['is a letterpress man at a printer\'s in Salem', 'I print wedding invitations in Salem. Printed Helen Novak\'s. Cream stock, engraved. I cried a little, don\'t tell anybody.'],
  ],
  f: [
    ['packs sardines at Harbor Canning, weekdays', 'I pack sardines weekdays. You never get the smell out of your hands, but you get used to it, and so does your husband.'],
    ['is an operator at the telephone exchange', 'I\'m on the switchboard weekdays. “Number, please.” Hazel Oakes trained me. I listen much less than she did.'],
    ['sews piecework at home for Silva\'s', 'I do piecework for Mrs. Silva — hems, buttons. Four bridesmaids\' dresses this week. I could sew in my sleep. I have.'],
    ['works at the lunch counter at Woolcott\'s', 'Grilled cheese, twenty cents. The high school says it\'s the best in the county. I say it\'s the only grilled cheese in the county.'],
    ['is a secretary at the Trust Building', 'I type for an attorney on the ninth floor. Pratt Secretarial, class of \'46. A Pratt girl is always employed, Miss Pratt says. She\'s right.'],
    ['takes in sewing and alterations for half of Maple Street', 'I let out more waistbands after Thanksgiving than Adler & Son. Don\'t tell Isaac.'],
    ['keeps the books for the family business', 'I do the books. He does the work. I do the worrying. It\'s a partnership.'],
  ],
};

// ---------------------------------------------------------------- workplaces: building name → trade key
export const TRADE_OF = [
  [/Bakery/, 'bakery'], [/Meats/, 'butcher'], [/Laundry/, 'laundry'], [/Tailor/, 'tailor'], [/Fish Market/, 'fishmarket'], [/Fish Co/, 'fishco'],
  [/Pharmacy/, 'drugstore'], [/Barber/, 'barber'], [/5 & 10/, 'dime'], [/Florist/, 'florist'], [/Millinery/, 'hats'], [/Toys/, 'toys'],
  [/Jewel(?!ry)|Jewelers/, 'jeweler'], [/Dress/, 'dress'], [/Music/, 'music'], [/Hardware/, 'hardware'], [/Kowalski|Market$/, 'grocery'],
  [/Sweet/, 'candy'], [/Tobacco/, 'tobacco'], [/Tavern|Anchor/, 'bar'], [/Chandlery/, 'chandlery'], [/Rooms/, 'boarding'],
  [/Books/, 'books'], [/Radio &/, 'radio'], [/Photograph/, 'photo'], [/Luncheonette/, 'luncheonette'], [/Diner/, 'diner'],
  [/Shoes/, 'shoes'], [/Travel/, 'travel'], [/Loan & Jewelry/, 'pawn'], [/Furniture/, 'furniture'], [/Garage/, 'garage'], [/Esso/, 'gas'],
  [/Clam/, 'clam'], [/Canning/, 'cannery'], [/Courier/, 'newspaper'], [/Hotel/, 'hotel'], [/Union Station/, 'station'],
  [/Post Office/, 'post'], [/Library/, 'library'], [/Hospital/, 'hospital'], [/Savings|Bank|Trust Company/, 'bank'], [/Police/, 'police'],
  [/Engine Company/, 'fire'], [/School/, 'school'], [/Rialto/, 'theater'], [/Harlow/, 'department'], [/Lanes/, 'bowling'],
  [/Blue Lantern/, 'club'], [/Church|Rectory/, 'church'], [/Trust Building/, 'trust'], [/Boat Works/, 'boatworks'], [/Ice/, 'ice'],
  [/Pier|Freight|Cargo|Waterfront/, 'docks'], [/Harbor Master/, 'harbormaster'], [/Museum/, 'museum'], [/Yacht/, 'yacht'], [/Elks/, 'lodge'],
  [/Tackle/, 'tackle'], [/City Hall/, 'cityhall'], [/Gray Lady/, 'ship'], [/Mercantile|Beacon|Insurance|Savings & Loan/, 'office'], [/Park/, 'park'],
];

// first-person lines about working there. {building} = the building's name.
export const TRADE_LINES = {
  bakery: ['Up at four for the centennial loaves. Four hundred! Mr. Halloran stamped every one with the town seal himself.', 'Get here before seven and it\'s still warm. After seven, it\'s still Halloran\'s.', 'Nora Halloran\'s soda bread, 1887. We cut a cross on top to let the fairies out. Mr. Halloran says it\'s tradition. I think he believes in the fairies.'],
  butcher: ['Old Mr. Russo\'s sausage has six blue ribbons. He weighs with his thumb off the scale. You\'d be amazed how rare that is.', 'Chuck roast for the wedding people, soup bones for anybody who asks. That\'s how Mr. Russo runs it.'],
  laundry: ['Starch, heavy — that\'s how Captain Whitcomb\'s son liked it, and that\'s how Mr. Lee still does the Mayor\'s collars.', 'Forty shirts before noon. The Mayor\'s collars first. He turns his head a lot when he speaks.'],
  tailor: ['Old Mr. Adler still cuts every suit by hand. Forty-seven years. I just press, and listen to him argue.', 'We took in Robert Brennan\'s wedding suit three times. Nerves. It\'s always nerves.'],
  fishmarket: ['Haddock, twenty-nine cents! The boats were in at six. You can\'t get it fresher unless you swim for it.', 'Mr. Castellano\'s nephew came home Tuesday. The whole market\'s been smiling since. Even the fish.'],
  fishco: ['Fleet was in at six. We\'ve cut and iced twelve thousand pounds since. My hands don\'t feel like hands.', 'The old Pier 3 went out to sea in \'38 with three good men. There\'s a plaque on the new one. I touch it every morning. Everybody does.'],
  drugstore: ['Saturday afternoons the soda fountain belongs to the high school. Mr. Mayhew says it\'s good for business. His ears say otherwise.', 'Take one every four hours, with water. Not with coffee. Everybody takes it with coffee.'],
  barber: ['Everybody tells the barber everything. The trick is, the barber tells nobody. Marcus taught me that my first day.', 'Shave and a haircut, and the Red Sox score for free.'],
  dime: ['Four hundred pennants by ten! Mr. Woolcott has us looking in the stockroom for more.', 'Everything from thread to goldfish. You\'d be surprised how many people come in for thread and leave with a goldfish.'],
  florist: ['A wedding, a christening, the Mayor\'s podium and the time capsule, all in one day, and the Bower sisters aren\'t speaking. I carry messages. “Tell your sister...”'],
  hats: ['Madame Gould says the hat is not dead. I\'m not going to be the one to tell her otherwise.'],
  toys: ['Old Mr. Draper runs the train in the window himself. The boys have worn a groove in the sidewalk out front.'],
  jeweler: ['Mr. Weiss sets every clock in the shop by the station clock at 8:59. Every morning. If you\'re in here at 8:59, don\'t speak.'],
  dress: ['Four bridesmaids in pink taffeta this week, and the bride\'s gown to press. Mrs. Silva said “straighter” eleven hundred times.'],
  music: ['Every record in the store is going to the sock hop tonight. Mr. Bishop\'s counted them twice.'],
  hardware: ['Tom Garrity\'s father opened this place in 1904, selling nails to the men who rebuilt Market Street. The first dollar\'s on the wall by the register.', 'Can\'t keep television antennas on the shelf. Everybody wants one. Half of them haven\'t got the television yet.'],
  grocery: ['In \'34 old Mr. Kowalski crossed out every striker\'s debt in the credit book. “Paid. All of it.” Nobody had paid anything. That\'s why this street shops here.'],
  candy: ['Penny candy is still a penny here. Mr. Kouris says he\'s a fool. He says it smiling.'],
  tobacco: ['The Boston papers come in on the 9:02 and they\'re gone by ten. Everybody wants the Marciano fight.'],
  bar: ['No singing before nine. After nine, God help us.', 'That glass of rum under the MARY ELLEN picture — nobody drinks it. Nobody ever has.'],
  chandlery: ['Rope, paint, oilskins, compasses, tide tables. Mr. Carver throws in the advice for free. It\'s worth every penny.'],
  boarding: ['Supper at six SHARP. Mrs. Pruitt means it. I\'ve seen her lock the dining room door at 6:01.'],
  books: ['“The Old Man and the Sea” — sold out again. Every fisherman in town bought one to tell Miss Pike what Hemingway got wrong.'],
  radio: ['Seven sets sold in town in 1951. Sixty this year. On fight nights there are men three deep on the sidewalk watching our window.'],
  photo: ['Mr. Lowell\'s shooting the wedding at two, the capsule at half past five, and the fireworks at nine. I carry the plates and pray.'],
  luncheonette: ['Coffee and a cruller, fifteen cents, and we\'ll have you on the 6:10 with a minute to spare.', 'Mr. Lindqvist eats the same breakfast at 5:40 every morning. If he\'s ever late, Miss Beal says, the world is ending.'],
  diner: ['Chowder\'s Friday, pie is always. Nick says it like a prayer.', 'Mrs. Papadakis remembers every order in town. I\'ve got to write mine on my hand.'],
  shoes: ['Mr. Beaumont says everybody\'s arches are falling. Half the town comes in to find out if theirs are.', 'The X-ray machine lets you see your toes wiggle. The Halloran boy comes in three times a week just to look.'],
  travel: ['Every telegram from Korea came through this counter. Sal Castellano\'s from San Francisco too. DONT MAKE A FUSS STOP.', 'Niagara Falls, Bermuda, Montréal. Everybody\'s going somewhere this fall except me.'],
  pawn: ['Half the wedding rings in town have spent a winter in the back room here. Mr. Ellsworth never sells one if he can help it.'],
  furniture: ['A little down and a little each week. Half the parlors on Maple Street came through this door on Mr. Tremblay\'s plan.'],
  garage: ['We keep the police cars, the delivery trucks and the fire engine running. Sign over the bench says WE FIX ANYTHING BUT THE RED SOX.'],
  gas: ['Twenty-nine cents a gallon, and I check your oil and your tires without being asked. Directions to Route 128 are free.'],
  clam: ['Fried clams, fifty cents the box. Mrs. Furtado doesn\'t skimp on the bellies and she doesn\'t let us either.'],
  cannery: ['Harbor Canning, since 1899. Sardines, mackerel, and the smell everybody pretends not to notice.', 'Forty tins a minute. Mr. Novak times us. Then he tells us about 1934.'],
  newspaper: ['Forty-eight pages tomorrow. The presses roll at half past nine. Miss Lowell hasn\'t sat down since Wednesday.'],
  hotel: ['Seventy rooms and every one booked for the centennial. There\'s a man from Hartford sleeping in the palm court.', 'Earl — Mr. Ives — has carried bags at the Whitcomb for thirty-one years. He says the step by the door has never once moved.'],
  station: ['Four trains a day to Boston. The 4:52 has been on time since 1911. Mr. Lindqvist will tell you so. Often.'],
  post: ['Saturday delivery, centennial or no. Three-cent stamps, and a special cancellation for the collectors.'],
  library: ['Shh. Miss Mayhew can hear a page turn from the reference room.'],
  hospital: ['Mrs. Kaminski\'s been in since midnight. Mr. Kaminski\'s been pacing since midnight. We\'re more worried about Mr. Kaminski.', 'St. Luke\'s was built by public subscription after the influenza. Every nickel in town is in these walls.'],
  bank: ['Saturday hours nine to noon. The first dollar deposited in 1871 is framed behind the tellers. Four thousand one hundred and twelve dollars that first year.'],
  police: ['Lost child, lost dog, lost wallet. Centennial day. Sergeant Duffy keeps peppermints for the children.'],
  fire: ['Polished that brass twice this morning. And at eleven — the cat. Again.', 'Old Faithful came in 1903, the year after the fire. We still polish her. She\'s earned it.'],
  school: ['The gym floor\'s waxed for the sock hop. Mr. Coleman will personally escort anybody in shoes back out to the street.'],
  theater: ['“Roman Holiday” at two, “Shane” at half past seven. Twenty-five cents. The boy yells “Shane! Come back!” and so does half the house.'],
  department: ['Five floors and the only escalator in the county. Old Mr. Harlow rides it twice a day, for inspection purposes.'],
  bowling: ['I set pins at Harbor Lanes. Nickel a line. Ted Kowalski bowls a two-ten and never once smiles.'],
  club: ['Late set at nine — the Earl Freeman Quartet. Tenor man up from Providence tonight. WJBY carries it live at eleven.'],
  church: ['Wedding at two, confessions at four. The bell rings at three for Helen and Robert. We\'ve got a new rope — the old one broke on V-J Day.'],
  trust: ['WJBY broadcasts from the twenty-first floor. The Mayor goes out live at half past five. Bill Ferris has asked him to stand CLOSE to the microphone.', 'Twenty-two storeys, finished three weeks before the Crash. The Trust never missed a payroll. Old Josiah Crane saw to that.'],
  boatworks: ['Forty-one wooden minesweepers came down these ways in the war. Mr. Yates built the copper box for the time capsule too — well, his apprentices did.'],
  ice: ['Ice in the summer, coal in the winter. The fish don\'t care which, as long as it\'s cold.'],
  docks: ['The GRAY LADY\'s discharging newsprint for the Courier. Two hundred and fourteen rolls yesterday. That\'s your Sunday paper, right there.', 'Freighter sails Monday at six for Portland and Halifax. The mate says wipe your feet.'],
  harbormaster: ['Fireworks barge anchored off the inner harbor at nine. All vessels two hundred yards clear. Mr. Hallett\'s written it on the board in capitals.'],
  museum: ['The old Custom House, 1859. Granite. The high-water line from \'38 is on the steps outside. The figurehead of the JUNIPER is inside. The Pruitts say it was their barn.'],
  yacht: ['The yacht club. Summer people, mostly. They\'ve gone home to Boston. It\'s just us and the gulls now.'],
  lodge: ['Elks Lodge 812. The Ladies\' Auxiliary rolled bandages here all through the war. Four years of bandages.'],
  tackle: ['Nets mended, lines spooled, bait and ice before dawn. The tide table\'s chalked on the door every morning.'],
  cityhall: ['The Old Granite Lady. In 1918 the council chamber upstairs was a hospital ward for six weeks. There\'s a plaque. Go and read it.'],
  ship: ['S.S. GRAY LADY, out of Boston. Crew liberty from six tonight, back aboard by half past eleven or the mate will know why.'],
  office: ['Most of the offices are closed Saturdays. Mr. Crosby of Hale & Crosby says he doesn\'t know what to do with himself.'],
  park: ['The oaks in Juniper Park were planted for the nine lost in the Great War. Mind the benches — they\'re all spoken for this afternoon.'],
};

// ---------------------------------------------------------------- the day, as people plan it (first person)
export const PLANS = {
  adult: [
    'I\'ll be down on the quay at nine for the fireworks. Best view is from the end of Pier 5, but don\'t tell anybody.',
    'I\'m going to hear the Mayor at half past five. Six pages. We\'ll see.',
    'We\'re going to the street dance tonight. First time in years. I\'ve pressed my good clothes.',
    'I\'ve been to the fair twice already. The candy apples are a nickel and the ring toss is crooked.',
    'I might go to the pictures — “Shane” at half past seven. Or the street dance. Or both. It\'s the centennial.',
    'I went down to watch the fleet come in at six. Gulls everywhere. You\'d think it was the gulls\' centennial.',
    'We\'re having the neighbors over after the fireworks. Pie and coffee. I made two pies, in case.',
  ],
  old: [
    'I\'ll watch the fireworks from my porch. I\'ve seen fireworks. I\'ve never seen a hundred years. Well — I\'ve nearly seen a hundred years.',
    'I\'m going to hear the Mayor. I heard his father speak in 1903 for the fifty years. He was shorter. The speech, I mean.',
    'I\'ll sit in Juniper Park this afternoon and listen to the band. They\'re playing old Pruitt\'s quickstep. First time in fifty years.',
  ],
};

// ---------------------------------------------------------------- greetings, by time of day (minutes)
export const GREETINGS = [
  [0, 270, ['You\'re up late.', 'Evening — or morning, I suppose.', 'Can\'t sleep either?', 'Mind how you go. It\'s dark as a pocket out.']],
  [270, 420, ['Morning! You\'re up early.', 'Mornin\'. Smell that? Halloran\'s ovens.', 'Early bird, eh?', 'Morning. Fleet\'s coming in — hear the gulls?']],
  [420, 600, ['Good morning!', 'Morning!', 'Mornin\'.', 'Fine morning for it, isn\'t it?', 'Morning! Happy centennial!', 'Top of the morning.', 'Morning — fair opens at ten!']],
  [600, 720, ['Good morning!', 'Happy Harbor Days!', 'Morning! Have you been to the fair?', 'Hello there!', 'Swell day for it!', 'Morning — isn\'t the square something?']],
  [720, 840, ['Afternoon!', 'Good afternoon.', 'Hello there!', 'Swell day for it!', 'Afternoon — you headed to the fair?', 'Happy centennial!']],
  [840, 1050, ['Afternoon!', 'Good afternoon.', 'Hello, hello!', 'Afternoon — did you see the bride?', 'Lovely afternoon, isn\'t it?', 'Afternoon! Going to hear the Mayor?']],
  [1050, 1090, ['Evening! Half past five — the Mayor!', 'Hello! Come stand over here, you can see the steps.', 'Evening — shh, is he starting?']],
  [1090, 1200, ['Evening!', 'Good evening.', 'Evening — lovely night.', 'Evening! Staying for the fireworks?', 'Evening! Did you hear the Mayor?']],
  [1200, 1260, ['Evening!', 'Good evening!', 'Evening — going down to the quay?', 'Evening! Hear the band on the square?', 'Evening — fireworks at nine!']],
  [1260, 1290, ['Look! Look up!', 'Oh — hello! Isn\'t it grand?', 'Evening! Did you see that one?']],
  [1290, 1440, ['Evening.', 'Good night, now.', 'Late one, isn\'t it?', 'Mind how you go.', 'Evening — wasn\'t that something?', 'Night! What a day, eh?']],
];

// ---------------------------------------------------------------- time-of-day talk (merged into activity chatter when the hour fits)
// [from, to, acts ('*' = any talkative act), lines]
export const TIME_TALK = [
  [270, 480, ['talk', 'talk_sit', 'eat', 'drink'], ['Fleet\'s in. Castellano\'s boats first, as usual.', 'Halloran\'s had the ovens going since half past four. Four hundred loaves!', 'Any coffee left?', 'Fog burned off early. Good sign for tonight.']],
  [480, 720, ['talk', 'talk_sit', 'browse', 'eat', 'drink'], ['The fair opens at ten on the square.', 'Bank\'s open till noon, if you need it.', 'Did you hear? Mrs. Hatch\'s cat is up the maple again.', 'Wedding\'s at two. St. Brigid\'s will be packed to the rafters.', 'Have you signed the Centennial Book yet?', 'Still no word from St. Luke\'s about the Kaminski baby.']],
  [660, 705, ['talk', 'cheer', 'look', 'watch'], ['There goes the ladder! Hold it steady, boys!', 'Five times since Easter, that cat.', 'Come DOWN, Admiral!', 'He\'s got him! No — he hasn\'t got him.']],
  [720, 840, ['talk', 'talk_sit', 'eat', 'drink', 'browse'], ['Band plays on the square at one.', 'Two o\'clock at St. Brigid\'s. Helen Novak\'s dress has two hundred and twelve pearls!', 'Musical chairs at the Moreaus\' — you can hear it from the street.', 'The matinee\'s “Roman Holiday.” Audrey Hepburn. Twenty-five cents.']],
  [840, 1030, ['talk', 'talk_sit', 'eat', 'drink', 'browse'], ['Did you see Helen come out of St. Brigid\'s? Like a picture.', 'The bell rang at three for the Novak wedding. I cried in the middle of Market Street.', 'Still no baby at St. Luke\'s. Poor Stan Kaminski.', 'Choir\'s practicing at First Congregational. You can hear Ruth Freeman from the park.', 'Who won the pies? Has anybody heard who won the pies?']],
  [1030, 1086, ['talk', 'talk_sit', 'listen', 'drink'], ['Half past five, the Mayor. Let\'s get up close.', 'Six pages, they say. Mrs. Pemberton\'s mercy.', 'WJBY\'s broadcasting it live. My mother\'s listening in Worcester.']],
  [1086, 1110, ['talk', 'listen', 'listen_sit', 'clap'], ['Shh — he\'s starting.', 'Hear, hear!', 'Can you see Miss Whitcomb? Bless her.', 'The capsule! There it goes!']],
  [1110, 1200, ['talk', 'talk_sit', 'eat', 'drink', 'watch'], ['What did you think of the speech?', 'Six pages. Felt like eleven.', 'When Miss Whitcomb put in the letter, I had to look away.', 'The Castellanos are having Sal Jr.\'s supper. You can smell the sauce from Church Street.']],
  [1155, 1260, ['talk', 'talk_sit', 'eat', 'drink', 'dance'], ['It\'s a girl! The Kaminskis — did you hear? Rose, seven pounds two ounces!', 'Stan Kaminski\'s handing out cigars on the hospital steps. He doesn\'t smoke.', 'Fireworks at nine. Are you going down to the quay?', 'Street dance on the square at eight. Harbor Days Band.']],
  [1260, 1290, ['talk', 'talk_sit', 'look', 'cheer', 'drink', 'dance'], ['Ooh! Look at that one!', 'The gold ones are the best.', 'That one looked like a chrysanthemum!', 'Biggest fireworks this harbor ever saw!']],
  [1290, 1440, ['talk', 'talk_sit', 'drink', 'dance', 'eat'], ['Best fireworks this harbor\'s ever seen. Joe Brennan said so and he\'s never wrong about fire.', 'The presses are rolling at the Courier. Sunday\'s paper will have all of it.', 'The light\'s on at the Point. Amos never misses.', 'What a day. What a hundred years.', 'Earl Freeman\'s late set is on WJBY at eleven.']],
];

// ---------------------------------------------------------------- overheard: what people say while doing things
// Hymns (sing) are public-domain texts, shown between ♪ ♪. Secular songs (sing_free) likewise.
const HYMNS = [
  '♪ Now thank we all our God, with heart and hands and voices ♪',
  '♪ Who wondrous things hath done, in whom his world rejoices ♪',
  '♪ Eternal Father, strong to save, whose arm hath bound the restless wave ♪',
  '♪ O hear us when we cry to Thee, for those in peril on the sea ♪',
  '♪ Brightly beams our Father\'s mercy from His lighthouse evermore ♪',
  '♪ Let the lower lights be burning! Send a gleam across the wave! ♪',
  '♪ Some poor fainting, struggling seaman you may rescue, you may save ♪',
  '♪ O God, our help in ages past, our hope for years to come ♪',
  '♪ Our shelter from the stormy blast, and our eternal home ♪',
  '♪ Blest be the tie that binds our hearts in Christian love ♪',
  '♪ Shall we gather at the river, where bright angel feet have trod ♪',
  '♪ Come, ye thankful people, come, raise the song of harvest home ♪',
  '♪ We gather together to ask the Lord\'s blessing ♪',
  '♪ Faith of our fathers, living still, in spite of dungeon, fire and sword ♪',
  '♪ For the beauty of the earth, for the glory of the skies ♪',
  '♪ Abide with me; fast falls the eventide ♪',
  '♪ Amazing grace, how sweet the sound ♪',
  '♪ Holy, holy, holy! Lord God Almighty! ♪',
  '♪ A mighty fortress is our God, a bulwark never failing ♪',
  '♪ Jesus, Savior, pilot me over life\'s tempestuous sea ♪',
  '♪ Rock of Ages, cleft for me, let me hide myself in Thee ♪',
  '♪ It is well, it is well with my soul ♪',
  '♪ Holy God, we praise Thy name; Lord of all, we bow before Thee ♪',
  '♪ O beautiful for spacious skies, for amber waves of grain ♪',
];
const SONGS = [
  '♪ Sweet Adeline, my Adeline... at night, dear heart, for you I pine ♪',
  '♪ Let me call you sweetheart, I\'m in love with you ♪',
  '♪ By the light of the silvery moon, I want to spoon ♪',
  '♪ Shine on, shine on, harvest moon, up in the sky ♪',
  '♪ Take me out to the ball game, take me out with the crowd ♪',
  '♪ Daisy, Daisy, give me your answer, do ♪',
  '♪ In the good old summertime, in the good old summertime ♪',
  '♪ My wild Irish rose, the sweetest flower that grows ♪',
  '♪ When Irish eyes are smiling, sure, \'tis like the morn in spring ♪',
  '♪ Sul mare luccica, l\'astro d\'argento... Santa Lucia! ♪',
  '♪ Sto lat, sto lat, niech żyje, żyje nam! ♪',
  '♪ Alouette, gentille alouette... ♪',
  '♪ Oh Shenandoah, I long to see you — away, you rolling river ♪',
  '♪ Oh, blow the man down, bullies, blow the man down ♪',
  '♪ Anchors aweigh, my boys, anchors aweigh! ♪',
  '♪ Happy birthday to you, happy birthday to you ♪',
];
const BAND_TUNES = ['♪ “The Stars and Stripes Forever” ♪', '♪ “In the Good Old Summertime” ♪', '♪ “Anchors Aweigh” ♪', '♪ “The Juniper Bay Quickstep” — L. Pruitt, 1903 ♪', '♪ “Semper Fidelis” ♪', '♪ “The Washington Post” ♪', '♪ “Sweet Adeline” ♪', '♪ “Over There” ♪'];
const JAZZ_TUNES = ['♪ “Stardust” ♪', '♪ “Body and Soul” ♪', '♪ “How High the Moon” ♪', '♪ “Sweet Georgia Brown” ♪', '♪ “Ain\'t Misbehavin\'” ♪', '♪ “St. Louis Blues” ♪', '♪ “Honeysuckle Rose” ♪', '♪ “The Sheik of Araby” ♪'];
const ORGAN = ['♪ “Now Thank We All Our God” — Crüger, 1647 ♪', '♪ Bach. Something with a great many notes. ♪', '♪ “Eternal Father, Strong to Save” ♪', '♪ The wedding march, from the top ♪', '♪ “A Mighty Fortress” ♪'];

export const ACT_LINES = {
  eat: [
    'Pass the potatoes, would you?', 'This is delicious.', 'Elbows off the table.', 'Is there any more gravy?', 'Mm. Just like my mother made.', 'Save room for pie.',
    'Who made the rolls? Halloran\'s? I knew it.', 'More chowder? There\'s always more chowder.', 'Don\'t talk with your mouth full, dear.', 'Salt, please. And the pepper. And the butter, while you\'re there.',
    'I shouldn\'t. Oh, all right. A small piece.', 'Eat your carrots. There are children in Europe who\'d be glad of those carrots.', 'Is this the haddock from this morning? You can taste the difference.',
    'Who wants the last pork chop? Nobody? ...I\'ll take it then.', 'Coffee\'s fresh. Help yourself.', 'Say grace first! Honestly.', 'Best pot roast on the North Shore.', 'Did you try the fudge from the Sweet Shoppe? Maple walnut, 1853 recipe.',
  ],
  drink: [
    'Another round?', 'To the centennial!', 'To the next hundred years!', 'Sláinte!', 'Salute!', 'Na zdrowie!', 'Saúde!', 'L\'chaim!', 'Yamas!', 'Skål!',
    'This root beer float is the living end.', 'Two straws, please.', 'Make mine a lime rickey.', 'A black-and-white frappe — heavy on the black.', 'I\'ll have what he\'s having. What is he having?',
    'One more and then home. That\'s what I said an hour ago.', 'To absent friends.', 'To the MARY ELLEN. To all of them.', 'Is that the Sox game on the radio? Turn it up.', 'Here\'s mud in your eye.',
  ],
  drink_stand: ['Cheers!', 'To Juniper Bay!', 'Down the hatch.', 'Here\'s to the Mayor\'s six pages.', 'Salute!'],
  talk: [
    'Did you hear about the Castellano boy? Home safe, thank God.', 'They say the Mayor\'s speech was eleven pages. Mrs. Pemberton cut it to six.', 'Helen Novak\'s dress — every pearl sewn by hand. Two hundred and twelve!',
    'The fireworks go off at nine, over the harbor.', 'A hundred years. Can you imagine?', 'My grandfather helped raise the meetinghouse in \'71. Fifty men in one day.', 'Mrs. Hatch\'s cat is up a tree again.',
    'Heard the Hallorans got a television. Twenty-one inches!', 'Weather\'s holding for the fireworks, knock wood.', 'My boy\'s playing trombone in the band tonight.', 'Isn\'t the square a picture with all the bunting?',
    'Have you been down to see the MARY ELLEN stone? Somebody left fresh flowers.', 'Stan Kaminski\'s been at St. Luke\'s since midnight. First babies.', 'Loretta Quimby pulled her pie. Did you hear why?',
    'Otto Lindqvist blew the whistle himself when Sal Jr. came home. Otto!', 'I still say Ted Williams is the best hitter who ever lived.', 'The price of coffee! Ninety-three cents!', 'They\'re putting forty new lamps on Harbor Street. Mercury vapor. Bright as noon, they say.',
    'Have you signed the Centennial Book?', 'My mother came over in 1908 with nothing but a feather bed.', 'The Braves moved to Milwaukee. I\'ll never forgive them. Never.', 'Did you see the high-water line on the Custom House? Six feet. I get a chill every time.',
    'Who\'s going to win the pie contest, do you think?', 'The Bower sisters aren\'t speaking again.', 'They say Bill Ferris is sweet on Evelyn Sayer.', 'What do you suppose they\'ll think of us in 2053?',
    'My feet are killing me and it isn\'t even noon.', 'Isn\'t that the Fisk boy— no, he\'d be older now.', 'Well, I never.', 'And then he says to me — you\'ll never guess.', 'Oh, you don\'t say!',
  ],
  talk_sit: [
    'Well, I never.', 'And then he says to me...', 'Coffee?', 'Remember the \'38 hurricane? Water up to the second step.', 'More cake?', 'Now where was I?',
    'My sister in Worcester says they\'ve got the television too. Everybody\'s got the television.', 'You haven\'t changed a bit.', 'I told him and I told him.', 'Oh, the stories I could tell you about this town.',
    'Did you know my mother knew old Captain Whitcomb\'s granddaughter? Oh, yes.', 'I\'d better get off my feet a minute.', 'Do you remember when the trolley was free the first day?',
    'She\'s a lovely girl, that Helen Novak.', 'Put your feet up, dear.', 'That Castellano boy looks thin.', 'It\'s been a year, hasn\'t it? It\'s been a hundred years.',
  ],
  laugh: ['Ha! Oh, that\'s rich.', 'Stop, stop, I\'ll split my seams!', 'Oh, you\'re terrible.', 'Ha ha! That\'s the funniest thing I\'ve heard all year.', 'Don\'t make me laugh, I\'ve got a mouthful of fudge!'],
  watch: [
    'Shh! This is the good part.', 'Isn\'t she lovely?', 'Who is that fella?', 'Oh, I can\'t look!', 'Pass the popcorn.', 'I love this part.', 'Here it comes...', 'Oh, for heaven\'s sake.',
    'Look at him!', 'Did you see that?', 'Oh, I could watch this all night.', 'Shh — I can\'t hear.', 'Isn\'t that something?', 'What did he say?', 'I\'ve seen this one. Don\'t tell you how it ends? Fine.',
  ],
  read: [
    'Says here the cannery\'s hiring for the winter pack. See Mr. Novak Monday.', 'Listen to this: “Centennial Committee Expects Record Crowd.”', 'Red Sox lost again.', 'Marciano! Eleventh round!',
    'It says here the Ladies\' Auxiliary counted sixty-one pies. Sixty-one!', 'Stan Kaminski asked them not to print anything about the baby. So they printed that.', '“Welcome Home, Sal.” Oh, isn\'t that nice.',
    'Weather: fair and cool, clear for the fireworks. Knock wood.', 'Harlow\'s has ladies\' fall coats from nineteen ninety-five.', 'The Yankees clinched the pennant. Of course they did.', 'Hm. Hm. Well, I never.',
  ],
  read_book: ['Just one more chapter.', 'Hm. The butler, I think.', 'Miss Mayhew said I\'d love this one. Miss Mayhew was right.', 'I\'m reading “The Old Man and the Sea.” Every fisherman in town says it\'s wrong about the fish.'],
  read_stand: ['Paper says fair weather through Sunday.', 'Says the Courier will run forty-eight pages tomorrow.', 'Marciano in eleven! A Brockton boy!', 'Ha. Look at this. The Mayor\'s picture again.'],
  write: ['Dear Mother...', 'How do you spell “centennial”? Two n\'s?', 'Dear David — well, the whole town turned out...', 'To the people of 2053: hello from Juniper Bay!', 'Now where was I.'],
  type: ['Clack clack clack... ding!', 'Forty words a minute, Miss Pratt says. I\'m at thirty-eight.', 'Where\'s the carbon paper?', 'Oh, drat. Where\'s the eraser?'],
  phone: ['Hello? Operator? Get me four-two-two-one-seven, please.', 'Hello? Hazel, I know you\'re on the line.', 'Any news from St. Luke\'s? No? Call me the minute.', 'Yes, Mother. Yes. Yes, Mother. I know, Mother.', 'Speak up, it\'s the party line!'],
  phone_stand: ['Hello? Hello? Can you hear me?', 'I\'ll be home by ten. Well, eleven. It\'s the centennial.'],
  browse: [
    'What do you think of this one?', 'Too dear. Maybe next week.', 'Do you have it in blue?', 'Just looking, thank you.', 'Oh, isn\'t that darling.', 'How much is this?',
    'I\'ll take two. No — three. It\'s the centennial.', 'Is that the same as last year\'s? It looks the same as last year\'s.', 'My husband would never wear that. I\'m buying it anyway.',
    'Do you have it in a larger size? For my sister. Not for me.', 'Could you put it aside for me till Friday?', 'Is this on the layaway plan?', 'Centennial pennants! I\'ll take one for each of the children.',
  ],
  counter: [
    'Next, please!', 'That\'ll be thirty-five cents.', 'Anything else today?', 'Fresh in this morning.', 'Will that be all?', 'Wrap it or will you carry it?',
    'Out of the ten, that\'s your change.', 'Oh, we\'ve got that in the back. Just a minute.', 'Happy centennial! Thank you, come again.', 'Cash or on account?', 'Hold on — I\'ll get the scale.',
  ],
  shelve: ['Soup on the left, beans on the right.', 'Who put the pickles with the jam?', 'Stock boy! Oh — that\'s me.', 'Three more boxes and I\'m done.'],
  serve: ['Here you are.', 'Mind, it\'s hot.', 'Anything else I can get you?', 'More coffee?', 'Save room — there\'s pie.'],
  bartend: ['What\'ll it be?', 'Another?', 'No singing before nine.', 'Last call\'s at one, centennial or no.', 'That one\'s on the house. Don\'t tell anybody.', 'Coffee for you, Lonnie.'],
  haircut: ['Little off the top?', 'Hold still now.', 'Sox are fourth again.', 'Look at that — you\'ve got a cowlick like your father.', 'Close shave, or a centennial shave?'],
  shine: ['Shine, mister? Ten cents.', 'Spit and polish — well, polish.', 'You could see your face in these. Go on, look.'],
  cook: ['Don\'t touch that, it\'s hot!', 'Supper in twenty minutes!', 'Now where did I put the paprika?', 'Taste this. More salt?', 'Out of my kitchen, all of you!', 'Who ate the crust off this pie?', 'Order up!', 'Mind the grease.'],
  wash: ['Many hands make light work, you know.', 'You dry, I\'ll wash.', 'Who used every pot in the house?', 'Careful with Grandma\'s platter!'],
  sweep: ['Confetti everywhere. Centennial confetti.', 'Where does all this sand come from? Oh — the beach.', 'There. Clean as a whistle.'],
  mop: ['Mind the wet floor!', 'Wipe your feet, please.'],
  rake: ['Every leaf in the county lands in my yard.', 'The maples are just starting to turn. Give it two weeks.', 'I rake, the wind unrakes.', 'Jump in that pile and you\'re raking the next one.'],
  shovel: ['Who ordered all this dirt?', 'Put your back into it.'],
  water_plants: ['The mums are coming along.', 'Last tomatoes of the year.', 'Drink up, you poor things.'],
  garden: ['Last tomatoes of the season.', 'Bulbs in by Columbus Day, my mother always said.', 'Mums for the centennial. Bronze and gold.', 'Who\'s been in my beans?'],
  laundry: ['Good drying weather — westerly wind.', 'Sheets out, sheets in. Rain by morning, maybe.', 'Where do the socks go? Every week, one sock.', 'Pinned out by eight. That\'s Monday wash on a Saturday for you.'],
  iron: ['Starch, heavy.', 'Mind the collar.', 'His good shirt for tonight. Heaven help him if he spills.'],
  sew: ['Ouch. Thimble, thimble...', 'One more button and it\'s done.', 'Straighter. Always straighter.'],
  knit: ['Knit two, purl two...', 'Two more rows and the scarf is done.', 'It\'s for the Kaminski baby. Yellow. Hedging, like Opal.', 'Drat. Dropped one.'],
  rock: ['Ah, that\'s better.', 'When I was a girl this was all orchard.', 'Hundred years. I\'ve seen seventy of them myself.', 'Sit a while.'],
  pray: ['Eternal rest grant unto them, O Lord.', 'For those in peril on the sea.', 'God rest them, every one.', 'Hail Mary, full of grace...', 'Our Father, who art in heaven...'],
  pray_sit: ['Our Father, who art in heaven, hallowed be Thy name...', 'Hail Mary, full of grace, the Lord is with thee...', 'Bless Helen and Robert, and the baby at St. Luke\'s.', 'Amen.'],
  listen: ['Shh.', 'Isn\'t this something?', 'Can you see? I can\'t see.', 'Lovely.', 'Hear, hear.', 'I\'m going to cry.', 'Oh, isn\'t that nice.'],
  listen_sit: ['Shh.', 'Lovely.', 'Isn\'t it beautiful?', 'I always cry at these.', 'Can you see her?', 'Doesn\'t she look a picture.'],
  clap: ['Bravo!', 'Hear, hear!', 'Hooray!', 'Well done!'],
  clap_sit: ['Bravo!', 'Hooray!', 'Happy birthday!'],
  cheer: ['Hooray!', 'Hip hip — hooray!', 'Atta boy!', 'Whoopee!', 'Three cheers for Juniper Bay!', 'Go get him, Chief!'],
  look: ['Ooooh!', 'Aaaah!', 'Look at that one!', 'The gold ones are the best.', 'That one looked like a chrysanthemum!', 'Oh — did you feel that one in your chest?', 'Biggest ever!', 'Look how it lights up the lighthouse!'],
  wave: ['Yoo-hoo!', 'Over here!', 'Hello-o!', 'Bye now!'],
  hug: ['Oh, look at you!', 'Come here, you.', 'Welcome home, welcome home.'],
  cry: ['I always cry at weddings.', 'I\'m not crying. It\'s the chrysanthemums.', 'Oh, don\'t mind me.'],
  pet_dog: ['Who\'s a good boy?', 'Sit. Sit. Oh, never mind.', 'Don\'t feed him fudge!'],
  feed_birds: ['Here, birdie, birdie.', 'Don\'t be greedy, you.', 'The gulls take it all. Shoo!'],
  photograph: ['Say cheese!', 'Hold still — one more!', 'Everybody squeeze in!', 'Lovely. Once more for luck.'],
  toast: ['To the centennial!', 'To the bride and groom!', 'To absent friends.', 'Sto lat!', 'Salute!', 'Sláinte!', 'L\'chaim!', 'To the next hundred years!'],
  toast_sit: ['To Sal — home safe!', 'To the happy couple!', 'Cheers!', 'Salute!'],
  smoke_pipe: ['Ah.', 'Fog by morning, I\'d say.', 'I remember when this was all wharves.', 'Hm. A hundred years.'],
  hail_taxi: ['Taxi!', 'Yoo-hoo — cab!'],
  carry: ['Heads up! Crate coming through.', 'Mind your backs!', 'Where does this one go?', 'Lift with your legs!'],
  wrench: ['Hand me the nine-sixteenths.', 'Stubborn — stubborn — there.', 'Who tightened this, Hercules?'],
  under_car: ['Pass me the drop light.', 'Oil pan\'s leaking again.', 'Don\'t start it!'],
  hammer: ['Measure twice, nail once.', 'Ow. Ow. Ow.', 'Since \'38 I nail everything twice.'],
  saw: ['Stand back.', 'Right on the line.'],
  paint: ['Wet paint!', 'Centennial white, second coat.'],
  lean: ['Nice night for it.', 'Seen the paper today?'],
  wait: ['Trolley\'s late. Lloyd Finch is never late.', 'Any minute now.', 'I\'ve been waiting since Tuesday. Well, since ten.'],
  sit: ['Lovely day for it.', 'My feet are killing me.', 'Just resting my eyes.', 'Look at all the people.', 'A hundred years. Imagine.', 'Sit down a minute, the fair will keep.'],
  pace: ['Any news? Any news yet?', 'What\'s taking so long?', 'Is that normal? That can\'t be normal.', 'Nurse? Nurse!'],
  play: ['Tag, you\'re it!', 'Can\'t catch me!', 'Olly olly oxen free!', 'My turn! My turn!', 'No fair!', 'I\'m the Lone Ranger. You be Silver.', 'Bang! You\'re dead! No, I got you first!', 'Ready or not, here I come!', 'Home free!'],
  play_ball: ['Throw it here!', 'Over here, over here!', 'I\'m Ted Williams!', 'Easy out! Easy out!', 'Mine! Mine! ...Yours.', 'Batter up!', 'Aw, it went in Mrs. Hatch\'s yard again.'],
  jump_rope: ['Cinderella, dressed in yella, went upstairs to kiss a fella...', 'One, two, three, four, five, six...', 'Teddy bear, teddy bear, turn around...', 'Miss Mary Mack, Mack, Mack, all dressed in black, black, black...', 'Faster! Faster! Red hot pepper!'],
  hopscotch: ['One, two, three — hop!', 'You stepped on the line!', 'My turn!'],
  swing: ['Higher! Higher!', 'Push me!', 'I can see the lighthouse from up here!', 'Watch me jump off! ...Tomorrow.'],
  fish: ['Nibble... nibble... nothing.', 'You should\'ve seen the one that got away.', 'Mackerel are running tonight.', 'Pollock again. Always pollock.', 'Shh, you\'ll scare them.', 'Got one! No. Seaweed.'],
  fish_sit: ['Patience. That\'s all fishing is. Patience and a sandwich.', 'Tide\'s turning.', 'Not a bite since noon.', 'Amos Fisk took a fifty-one-pound striper off the Ledge in \'49. I\'d settle for a scup.'],
  chess: ['Check.', 'Hm. Hm. Hmm.', 'Your move.', 'Touch a piece, move a piece.', 'I\'ve been planning that for twenty minutes.', 'Checkmate. I think. Is it? It is!'],
  cards: ['I\'ll see your nickel and raise you a dime.', 'Read \'em and weep.', 'Fifteen-two, fifteen-four, and a pair is six.', 'Gin!', 'Who dealt this mess?', 'Pinochle! Double pinochle!', 'You\'re cheating. You\'re always cheating.'],
  bowl: ['Strike!', 'Spare! Spare counts!', 'Gutter ball. Again.', 'Ten-pin, ten-pin, ten-pin...', 'Ted Kowalski bowled a two-ten Thursday and didn\'t smile once.'],
  dance: ['You\'re a swell dancer.', 'Don\'t step on my toes this time!', 'They\'re playing our song.', 'One more? One more.', 'Isn\'t the band grand?', 'Whirl me round again!', 'My feet! Keep going.', 'I haven\'t danced like this since V-J Day.'],
  dance_jitterbug: ['Go, daddy-o!', 'This record is the most!', 'Shoes off — Mr. Coleman\'s orders!', 'Watch me spin!', 'Crazy, man, crazy!', 'Hey, that\'s my foot!', 'Play it again!', 'Is that Buddy Keene singing along? Somebody stop him.'],
  sing: HYMNS,
  sing_free: SONGS,
  conduct: ['From the top!', 'Altos, you\'re dragging!', 'Breathe at the comma, not before.', 'Beautiful. Again.'],
  announce: [
    'This is WJBY, the Voice of the Bay, 1340 on your dial.', '...and now a word from Halloran & Sons, bakers since 1887.', 'The time at the tone is...', 'Live from Founders Square — the Juniper Bay Centennial!',
    '...weather for tonight: fair and cool, perfect for fireworks.', '...and remember, Harlow\'s Centennial Sale continues through Saturday.',
  ],
  speech: ['Friends and neighbors...', 'One hundred years ago...', 'Steadfast in fair weather and foul!', 'And so, in conclusion — well, nearly in conclusion...'],
  teach: ['And one, two, three — and one, two, three...', 'Eyes on your own work, please.', 'Again, from the top.', 'Very good. Now faster.'],
  exam: ['Say “ah.”', 'Breathe in. And out.', 'Does this hurt? How about this?', 'Nothing a good night\'s sleep won\'t fix.'],
  microscope: ['Hm. Interesting.', 'Just as I thought.'],
  blow_candles: ['Whoosh!', 'I got them ALL!'],
  lie_grass: ['Look, that cloud\'s a schooner.', 'Last warm Saturday of the year, I bet.', 'I could stay here all day.'],
  sunbathe: ['Last bit of summer.', 'The water\'s like ice. Don\'t even think about it.'],
  // instruments: what's playing
  trumpet: BAND_TUNES, trombone: BAND_TUNES, tuba: BAND_TUNES, clarinet: BAND_TUNES, drum: BAND_TUNES, fiddle: SONGS.slice(0, 9),
  piano: JAZZ_TUNES, bass: JAZZ_TUNES, drum_sit: JAZZ_TUNES, guitar: JAZZ_TUNES, organ: ORGAN,
  doze: [],
  sleep: [],
};

// ---------------------------------------------------------------- what people say at work (by job role)
export const JOB_LINES = {
  baker: ['Rye, pumpernickel, and the centennial loaf — with the seal pressed on top.', 'Get here before seven and it\'s still warm.', 'Four hundred loaves before breakfast. My arms are bread.', 'Soda bread, cut a cross on top to let the fairies out.'],
  butcher: ['Two pounds of chuck? Coming right up.', 'Sausage is fresh — the blue-ribbon kind.', 'Soup bones are free for anybody who asks.', 'Lamb chops, nice and lean, for the lady.'],
  barber: ['Next! Oh — just looking? Suit yourself.', 'Little off the sides?', 'Shave and a haircut, and the Red Sox for free.', 'Hold still, now.'],
  shoeshine: ['Shine, mister? Ten cents.', 'You could see your face in these.'],
  police: ['Move along, folks, keep the crosswalk clear.', 'Lost a glove? Try the desk at headquarters.', 'Mind the curb, ma\'am.', 'Keep to the sidewalk — the fireworks crowd\'ll be thick tonight.'],
  fire: ['Engine One, finest in the county.', 'Polished that brass twice this morning. Centennial, you know.', 'Two pumpers on the quay tonight, just in case.', 'Five times since Easter, that cat.'],
  cook: ['Order up!', 'Two eggs, over easy, hash on the side.', 'Chowder\'s on Friday. Pie is always.', 'Who ordered the pot roast?', 'Hot plate — mind your hands!'],
  waitress: ['What\'ll it be, hon?', 'Pie\'s apple, cherry, and blueberry. Blueberry\'s the ticket.', 'Coffee, black? I knew it.', 'Be right with you, dear.', 'Special today is Yankee pot roast.'],
  counterman: ['Coffee and a cruller? Fifteen cents.', 'You\'ll make the train. Sit.', 'Blue plate\'s pot roast.'],
  dishwasher: ['Who ordered all these plates?', 'Somebody bring me a clean apron.'],
  clerk: ['Can I help you find something?', 'That\'ll be forty cents.', 'We close at six on Saturdays.', 'Wrap it up for you?', 'Anything else today?'],
  shopkeeper: ['Anything else for you today?', 'Fresh in this morning.', 'Centennial special — ten percent off.', 'Come again!'],
  proprietor: ['My father opened this store. His father would\'ve, if he\'d had the nails.', 'Anything else for you?', 'We\'ve got it, or we can get it.'],
  salesman: ['Can I show you something?', 'That\'s solid maple. Your grandchildren will fight over it.', 'A little down and a little each week.', 'Try it on — no obligation.'],
  saleslady: ['Oh, that\'s your color.', 'We can take it in for you by Tuesday.', 'Try the blue.'],
  seamstress: ['Straighter. Always straighter.', 'One more hem and I\'m done.'],
  tailor: ['A machine doesn\'t know a man\'s shoulders.', 'Hold your arms out. Now breathe. Now don\'t.', 'Pinch here, let out there.'],
  presser: ['Starch, heavy.', 'Mind the collar.', 'Forty shirts before noon.'],
  fishmonger: ['Haddock, fresh this morning!', 'Mackerel! Cod cheeks!', 'Twenty-nine cents a pound, and I\'ll clean it for you.', 'You want the head? For the soup? Smart.'],
  'fish cutter': ['Mind the knife.', 'Twelve thousand pounds since six.', 'Haddock, haddock, pollock, haddock.'],
  'net mender': ['Every hole\'s a story.', 'Tide\'s turning. Hand me the twine.'],
  iceman: ['Ice! Mind your toes!', 'Fifty pounds for the fish market.'],
  pharmacist: ['Take one every four hours, with water. Not with coffee.', 'Your prescription\'ll be ten minutes.', 'Aspirin? Second shelf.'],
  'soda jerk': ['One black-and-white frappe, coming up!', 'Two straws? I get it.', 'Root beer float? The best in town.', 'Cherry phosphate for the lady!'],
  florist: ['White roses and stephanotis for the bride.', 'Chrysanthemums, bronze and gold, for the centennial.', 'Carnations? If you must.'],
  milliner: ['The hat is not dead.', 'Tilt it — no, the other way. There.', 'Dove-gray is very flattering.'],
  jeweler: ['Engraving\'s free for a centennial bride.', 'A charm bracelet? Fourteen dollars. Or a little each week.'],
  watchmaker: ['Set by the station clock at 8:59. Never wrong.', 'Your mainspring\'s tired. So am I.'],
  grocer: ['Kielbasa\'s fresh this morning.', 'We deliver. Telephone four-one-eight.', 'Heel of the rye for you, Mrs. Hatch? I saved it.'],
  'stock boy': ['Soup on the left, beans on the right.', 'I\'ll get it down for you.'],
  candymaker: ['Saltwater taffy, pulled this morning!', 'Centennial fudge, maple walnut, fifty-nine cents a pound.', 'Penny candy is still a penny here.'],
  tobacconist: ['Cigar? Pipe tobacco? The Courier?', 'The Boston papers are in. Marciano in eleven!', 'Lighters filled free.'],
  newsdealer: ['Paper! Get your Courier!', 'Boston papers came in on the 9:02.'],
  'travel agent': ['Niagara Falls, Bermuda, Montréal — where to?', 'The 6:10 to Boston connects to everywhere.'],
  telegrapher: ['Ten words or less, forty-five cents to Boston.', 'Telegram for you — good news, for a change.'],
  pawnbroker: ['Six percent, thirty days.', 'I don\'t buy sob stories. I listen to them.', 'It\'s not for sale. It\'s being kept.'],
  chandler: ['Rope, paint, oilskins, compasses.', 'Tide tables are free. Knowing what to do with them costs extra.'],
  landlady: ['Supper is at six. Sharp.', 'No hot plates. I can smell a hot plate.', 'Doors lock at eleven.'],
  'hired girl': ['Mrs. Pruitt says the stairs twice a day.', 'Supper\'s at six. Don\'t be late, she means it.'],
  bookseller: ['“The Old Man and the Sea”? Sold out again.', 'Have you read the Christie? Nobody ever regrets the Christie.', 'That\'s Mr. Hawthorne. Don\'t mind him.'],
  repairman: ['It\'s a tube. It\'s always a tube.', 'Your antenna\'s pointing at Providence.'],
  photographer: ['Say cheese!', 'Hold still — no, you moved.', 'Everybody squeeze in.'],
  receptionist: ['May I help you?', 'Please have a seat. He\'ll be right with you.', 'Sign here, please.'],
  mechanic: ['She needs a new fan belt.', 'Twenty-nine cents a gallon. Fill her up?', 'We fix anything but the Red Sox.'],
  attendant: ['Fill her up?', 'Check your oil?', 'Route 128? Straight on, then left at the church.'],
  longshoreman: ['Heads up! Crate coming through.', 'Freighter\'s loading for Halifax on Monday.', 'Newsprint for the Courier. Mind the rolls.'],
  stevedore: ['Heave!', 'Mind your backs!'],
  'freight handler': ['Heads up!', 'Where does this one go?'],
  'hatch tender': ['Lower away! Easy!', 'Hold it — hold it — there.'],
  'cargo checker': ['Two hundred and fourteen rolls. Check.', 'That\'s not on my manifest.'],
  'harbor master': ['All vessels two hundred yards clear of the barge tonight.', 'No anchoring in the inner harbor after eight.'],
  boatbuilder: ['A boat ought to be a tree first.', 'Oak and fir, not a nail of iron below the waterline.'],
  apprentice: ['Mr. Yates says measure twice.', 'We made the copper box for the time capsule!'],
  custodian: ['Shoes off on my gym floor.', 'Mind the wet floor.', 'Twenty-eight years I\'ve kept this building.'],
  sexton: ['The bell rings at three for the wedding.', 'Mind the steps — they\'re granite and they don\'t forgive.'],
  priest: ['Peace be with you.', 'Confessions at four.'],
  organist: ['Again, from the top!', 'The altos are dragging.'],
  clergy: ['Peace be with you.', 'God bless you.'],
  'town clerk': ['Births may be registered weekdays. Fathers please remain calm.', 'The office closes at one for the centennial.'],
  secretary: ['The Mayor is not to be disturbed. He\'s cutting his speech. Again.'],
  announcer: ['This is WJBY, the Voice of the Bay.', 'Live from the City Hall steps at five-thirty.'],
  engineer: ['Levels are good. Tell the Mayor to stand closer.'],
  'transmitter engineer': ['Five thousand watts, clear to Portland tonight.'],
  'elevator operator': ['Going up! Watch your step.', 'Twenty-one: WJBY. Twenty-two: the terrace.', 'Main floor, main floor.'],
  doorman: ['Good afternoon, sir.', 'Mind the revolving door.'],
  'terrace attendant': ['Ten cents for the telescope. You can see Gannet Ledge.'],
  'committee secretary': ['Two thousand programs, and we\'re already out of programs.', 'The fireworks barge is confirmed. Don\'t ask what it cost.'],
  'committee volunteer': ['Sign the Centennial Book! It goes in the capsule.'],
  teller: ['Next window, please.', 'We close at noon on Saturdays.', 'Would you like that in fives?'],
  manager: ['Everything all right here?', 'Centennial sale ends tonight.'],
  bookkeeper: ['The books balance. Don\'t ask me how.'],
  bartender: ['What\'ll it be?', 'No singing before nine.', 'Last call\'s at one.', 'That one\'s on the house.'],
  'hat check': ['Your ticket, sir.', 'Mind you don\'t lose it.'],
  bandleader: ['A-one, a-two...', 'Late set\'s at nine.'],
  musician: ['From the top.'],
  pinsetter: ['Heads up down there!', 'Nickel a line.'],
  'desk clerk': ['Room 212, sir. Very lucky number, this year.'],
  'night clerk': ['Quiet night. Well — it will be, after the fireworks.'],
  bellhop: ['Right this way, sir.', 'Mind the step — it\'s been there since 1896.'],
  'maitre d': ['Table for two? Right this way.'],
  steward: ['Members only, I\'m afraid. Well — it\'s the centennial.'],
  housekeeper: ['Father\'s at the church. Can I give him a message?'],
  'typing student': ['Clack clack clack — ding!', 'The quick brown fox...'],
  'typing instructor': ['Eyes on your copy, not your keys.', 'Miss Pratt says the centennial is not an excuse.'],
  dentist: ['Open wide.', 'Just a little pinch.'],
  optometrist: ['Read the bottom line for me.', 'Better like this — or like this?'],
  doctor: ['Take two of these and call me Monday.', 'First babies take their time.'],
  nurse: ['Visiting hours end at eight.', 'Quiet, please — there are babies sleeping.', 'Mr. Kaminski, please sit down.'],
  attorney: ['I\'m afraid that\'s a matter for Monday.'],
  'insurance clerk': ['Fire, marine, life and automobile.'],
  'office clerk': ['File it under “C.” For Centennial.'],
  'loan officer': ['Your own roof. That\'s what we\'re here for.'],
  'union secretary': ['Dues are fifty cents. Bring a friend.'],
  'dance teacher': ['And one, two, three — and turn!'],
  'music teacher': ['Scales first. Then “Stardust.”'],
  'piano tuner': ['Plink. Plink. Plink. There.'],
  'clock winder': ['Two hundred and twelve turns of the crank. Every Saturday.'],
  'ticket agent': ['The ISLAND BELLE is at Pembroke for repairs. Try the launch.'],
  'boat hire': ['Skiff for the afternoon? Fifty cents.'],
  watchman: ['No visitors aboard without a pass.'],
  deckhand: ['Mate says wipe your feet.'],
  mate: ['Crew back aboard by half past eleven.'],
  'bait seller': ['Clams, worms, mackerel heads. Take your pick.'],
  'boat man': ['Row you out to see the fireworks from the water? A quarter.'],
  'counter girl': ['Fried clams, fifty cents.', 'Tartar sauce?'],
  'lunch counter': ['Grilled cheese, twenty cents.', 'Coffee with that?'],
  deliveryman: ['Delivery for Tremblay\'s! Where do you want it?'],
  'darkroom man': ['Don\'t open that door!'],
  'gear clerk': ['Sign here for the gear.'],
  'radio operator': ['Harbor Master to ISLAND BELLE, come in.'],
  'ice clerk': ['Fifty pounds or a hundred?'],
  cashier: ['Next!'],
  member: ['Hello, Brother. Good centennial?'],
  mail: ['Saturday delivery. Rain or shine or centennial.', 'Letter for you — from Korea, I think. No — from Worcester.'],
  milkman: ['One quart and a pint of cream, as usual.'],
  conductor: ['All aboard for Boston — oh, that\'s not till 5:35.', 'Tickets, please.'],
  'mail carrier': ['Saturday delivery. Rain or shine or centennial.', 'Nothing for you today but a seed catalogue.'],
  stationmaster: ['The 4:52 is on time. It\'s always on time.'],
  editor: ['Spell the names right.', 'Forty-eight pages. Nobody sits down till Sunday.'],
  linotype: ['Checked it nine times.'],
  librarian: ['Shh.', 'The centennial scrapbooks are in the reference room.'],
  teacher: ['Eyes front, please.', 'Who can spell “Massachusetts”?'],
  keeper: ['Light goes on at sundown.'],
  fisherman: ['Fleet was in at six. Good haddock, better mackerel.', 'Fog\'s coming in by morning. You can smell it.'],
  dock: ['Heads up! Crate coming through.', 'Freighter\'s loading for Halifax on the tide.'],
  foreman: ['Look lively! Twelve thousand pounds to cut before noon.', 'Ice on that — quick!'],
  packer: ['Forty tins a minute.', 'Line 3, all present.'],
  janitor: ['Shoes off on my gym floor.'],
};

// role names that should share a pool
export const ROLE_ALIAS = {
  shopkeeper: 'shopkeeper', 'shoe salesman': 'salesman', 'furniture salesman': 'salesman', 'television salesman': 'salesman', 'music store clerk': 'clerk',
  patrolman: 'police', 'desk sergeant': 'police', captain: 'fire', firefighter: 'fire', fireman: 'fire', minister: 'clergy', 'short-order cook': 'cook',
  'fountain girl': 'soda jerk', 'mail carrier': 'mail carrier', 'letter carrier': 'mail carrier', 'master baker': 'baker', 'butcher\'s helper': 'butcher',
  laundryman: 'clerk', 'master tailor': 'tailor', dressmaker: 'saleslady', toymaker: 'proprietor', 'hardware man': 'proprietor', 'hardware clerk': 'clerk',
  'candy counter girl': 'clerk', 'tackle man': 'clerk', 'ship chandler': 'chandler', 'chandlery clerk': 'clerk', 'radio repairman': 'repairman',
  'darkroom assistant': 'darkroom man', 'counter waitress': 'waitress', 'news-stand man': 'newsdealer', newsstand: 'newsdealer', 'elevator starter': 'elevator operator',
  janitor: 'custodian', superintendent: 'custodian', 'trust officer': 'teller', 'trust clerk': 'teller', broker: 'office clerk', 'branch manager': 'manager',
  agent: 'office clerk', accountant: 'bookkeeper', realtor: 'office clerk', notary: 'office clerk', physician: 'doctor', 'ferry ticket agent': 'ticket agent',
};
