// The named people of Juniper Bay, Saturday, September 26, 1953 — the Centennial.
//
// HOUSEHOLDS get placed in matching homes (by the home's special tag, building name or family);
// NOTABLES are townsfolk with particular jobs — notables sharing a surname form one household
// unless `own: true`. `home: { name }` can point at a shop (the flat upstairs) or at
// Mrs. Pruitt's Rooms (a lodger's room); if no such home exists, any free house is used.
// job: { building: '<exact building name>', role: '<job role registered by that building>' }
// Everyone also gets generated lines from sim/dialogue.js; `lines` here are their own.
//
// Keep this consistent with city/lore.js and with what the building generators say on their
// plaques and signs (honor rolls, the Pier 3 plaque, shop lore). Cross-references are deliberate:
// people mention each other by name, owe each other, courted each other, taught each other.
// Text uses straight apostrophes inside double-quoted strings and “curly quotes” for quotations.

// look helpers (see people/appearance.js: look.skin, look.hair (colour), look.face, look.hairStyle)
const SK = { fair: '#f3d6bd', light: '#ecc6a4', warm: '#e2b48e', olive: '#d4a07a', tan: '#bf8a62', brown: '#a06a45', dark: '#835236', deep: '#653e28' };
const HC = { black: '#1d1916', dark: '#34231a', brown: '#57391f', auburn: '#7a3a1c', red: '#a34a24', blonde: '#c8a45a', light: '#e0c586', gray: '#8f8a84', white: '#dcd8d0', salt: '#6f6a64' };
const HS = { short: 0, part: 1, bald: 2, long: 3, bob: 4, updo: 5, curly: 6, buzz: 7 };
const FC = { plain: 0, smile: 1, mustache: 2, glasses: 3, glassesMustache: 4, beard: 5, lipstick: 6, lashes: 7, freckles: 8, old: 9, rosy: 10, glassesLipstick: 11 };
const lk = (skin, hair, face, hairStyle, extra = {}) => ({ ...(skin ? { skin } : {}), ...(hair ? { hair, beard: hair } : {}), ...(face !== undefined && face !== null ? { face } : {}), ...(hairStyle !== undefined && hairStyle !== null ? { hairStyle } : {}), ...extra });

export const HOUSEHOLDS = [
  // ------------------------------------------------------------------ the Hallorans (the television)
  {
    surname: 'Halloran', home: { special: 'tv_dinner' }, homeName: 'Halloran Residence',
    members: [
      { first: 'Pat', age: 48, sex: 'M', role: 'baker', outfit: 'cook', job: { building: 'Halloran & Sons Bakery', role: 'baker' }, look: lk(SK.fair, HC.auburn, FC.mustache, HS.part),
        bio: "Patrick Halloran III, 48, the third Pat to run Halloran & Sons, which his grandfather opened on Market Street on May 2nd, 1887, with one oven and Nora Halloran's soda bread. Up at four, flour to the elbows, home by one. Fired the ovens at half past four this morning for four hundred centennial loaves, each stamped with the town seal. Bought the first television on Church Street in July and has regretted the antenna ever since.",
        lines: [
          "Four hundred centennial loaves, stamped with the town seal. My grandfather would've fainted dead away.",
          "Nora Halloran's soda bread, 1887. Same recipe, same crock. You cut a cross on top to let the fairies out. Don't let anybody tell you different.",
          "In '32 Pop sold the day-old for a penny and handed the rest out the back door. Never said a word about it. So neither will I.",
          "The committee wanted one of my loaves for the time capsule. Sealed! Shellacked! God help 2053. I threw in the stamp too, in case the bread doesn't make it.",
          "We bought an Admiral in July. Twenty-one inches. Now the whole street comes round for Jackie Gleason and nobody goes home.",
          "Irene's pie came second last year. Second! To Loretta Quimby. We don't say that name in the shop today.",
        ] },
      { first: 'Irene', age: 45, sex: 'F', look: lk(SK.fair, HC.brown, FC.lipstick, HS.curly),
        bio: "Irene Halloran, née Duffy, 45 — kid sister of Sergeant Augie Duffy. Runs the house, the books, and some say the bakery. Her apple pie (McIntosh from the old Pruitt orchard, lattice top, Pat's good butter) placed second at the 1952 fair — “robbed,” says the recipe card — and is entered again today.",
        lines: [
          "My pie's in the contest. Don't tell Pat I used his good butter.",
          "Loretta Quimby pulled her pie when she saw Father Garrity was judging. Says it's 1949 all over again. I say bake a better pie, Loretta.",
          "Supper's at six sharp — in front of the set, if you can believe it. Mother Halloran is scandalized.",
          "Peggy thinks I don't know who she's going to the sock hop with. I'm her mother. I knew before she did.",
          "My brother Augie's on the desk at headquarters all day. Lost children and lost dogs. He loves it, though he'd never say.",
          "My brother Francis — Frankie — was killed in the Argonne in October of 1918, two weeks before the Armistice. There's an oak for him in Juniper Park, third from the gate. Rose Bower still waters it.",
        ] },
      { first: 'Peggy', age: 16, sex: 'F', look: lk(SK.fair, HC.auburn, FC.freckles, HS.bob),
        bio: "Margaret “Peggy” Halloran, 16, a junior at Juniper Bay High. Junior bridesmaid at the Novak wedding at two (pink taffeta, taken up two inches by Mrs. Silva), then the Centennial Sock Hop at half past seven — officially with her friend Joanie, and also with a certain somebody her diary calls only “D.K.” Has entered a cherry pie in the contest. Against her own mother.",
        lines: [
          "The sock hop starts at half past seven. Not that I'm counting.",
          "I'm a junior bridesmaid at two, in pink taffeta. Then pin curls, then the sock hop. Then I'm going to lie down for a week.",
          "I entered a cherry pie. Against my own mother! She says it's healthy competition. She hid the cherries.",
          "I'm going with Joanie. I am! I'm going with Joanie. ...Did Tommy say something to you?",
          "Mr. Bishop's lending every record in the store. If he brings anything with a polka in it I'll just die.",
          "Did you see the pictures of Senator Kennedy's wedding in Newport? Two weeks ago today. Mother cried over the magazine.",
        ] },
      { first: 'Tommy', age: 11, sex: 'M', look: lk(SK.fair, HC.red, FC.freckles, HS.buzz),
        bio: "Thomas Halloran, 11. Stole home in the ninth last Saturday to beat Garrity Hardware 7–6 for the Castellano Fish Co. nine and has not stopped talking about it. Keeps his baseball cards in a cigar box marked DO NOT TOUCH — THIS MEANS YOU PEGGY, along with 212 bottle caps, counted. Has a dentist appointment at 10:15, on the Centennial, which he considers a crime.",
        lines: [
          "Didja see the fire engine? Mrs. Hatch's cat went up the maple again!",
          "I stole home in the ninth. Mr. Garrity says I was out. The ump said safe. The ump is the ump.",
          "I traded two Musials and a Kiner for a Mickey Mantle. And I got Ted Williams. He's back from Korea, he flew JETS, did you know that?",
          "I know who Peggy's sweet on. It'll cost you a nickel. Okay, two cents. ...Okay, his initials are D.K. That one's free.",
          "I gotta go to the dentist at ten-fifteen. On the CENTENNIAL. It's the molar. Ma's coming so I can't escape.",
          "Mr. Beaumont lets me look at my toes in the X-ray machine. Ma says three times a week is too many. How many is enough?",
        ] },
      { first: 'Bridget', age: 79, sex: 'F', title: 'Grandma', look: lk(SK.fair, HC.white, FC.old, HS.updo),
        bio: "Bridget Halloran, née Keane, 79, came from County Clare at sixteen. She was clerking at the ribbon counter at Harlow's the afternoon Market Street burned in 1902, left her post to follow a bucket brigade, and married the young man at the head of it — Pat's father — the next spring. Still keeps a bucket of sand by the back door. Does not hold with television, and has written “NO television during grace” on the cover of the TV Guide.",
        lines: [
          "I watched the whole of Market Street go up in nineteen-oh-two. Beal's livery first. The horses screaming. You don't forget the horses.",
          "Pat's father carried buckets past my counter at Harlow's all that afternoon. By spring I'd married him. Something good out of the ashes.",
          "A television at the supper table. In my day we said grace and talked to each other, God help us.",
          "My husband's baby brother Eddie went to France with the Yankee Division and stayed there. Château-Thierry, July of '18. His name's on the board at City Hall.",
          "In 1918 the influenza took my sister Kate. They laid her in the council chamber with the others. Say a prayer for her tonight.",
          "Girls in my day did not go to dances with boys whose fathers they didn't know. Peggy says everybody knows everybody's father. Well. That's true, God help us.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Castellanos (welcome home)
  {
    surname: 'Castellano', home: { special: 'welcome_home' },
    members: [
      { first: 'Sal', age: 58, sex: 'M', role: 'fisherman', job: { building: 'Castellano Fish Co.', role: 'fisherman' }, look: lk(SK.olive, HC.salt, FC.mustache, HS.short),
        bio: "Salvatore Castellano Sr., 58, runs Castellano Fish Co. on Pier 3, founded by his grandfather Giuseppe, who came from Sciacca, Sicily, in 1894 with one dory. Born in Sciacca himself; came over at three in his mother's arms. Three boats now, every one blessed by Father Garrity. His boy came home from Korea on Tuesday on the 4:52, and he has not stopped smiling since.",
        lines: [
          "My boy is home. My boy is home from Korea. You hear me? Home.",
          "Three boats, and every one blessed by Father Garrity. The GIUSEPPE, the LUCIA, and the little ROSA.",
          "The night Pier 3 went out in '38, Manuel Furtado stayed to cast off my boats. Him and the Kowalczyk boy and old Ernie Doane. I send his widow a haddock every Friday. It isn't enough. It's what I can do.",
          "We beat Garrity Hardware seven to six. The Halloran kid stole home. Tom Garrity still won't look me in the eye.",
          "Our price list is going in the time capsule. Haddock, twenty-nine cents. In 2053 they'll think we were saints or robbers.",
          "The winter before he enlisted, my son and I didn't speak. He took a room at Mrs. Pruitt's. Pride, the two of us. Tuesday I ran the length of the platform. Pride can go to the devil.",
        ] },
      { first: 'Rosa', age: 55, sex: 'F', look: lk(SK.olive, HC.dark, FC.smile, HS.updo),
        bio: "Rosa Castellano, 55, has been cooking for three days — arancini, caponata, a whole swordfish, and four kinds of cookies. Lit a candle at St. Brigid's every Sunday for the fourteen months her son was in Korea. When his telegram came from San Francisco — DONT MAKE A FUSS STOP I MEAN IT — she made a fuss. The whole block came.",
        lines: [
          "Mangia! There's enough for the whole of Church Street. Come at half past six. Bring a plate.",
          "I lit a candle every Sunday for fourteen months. Father Garrity says I kept St. Brigid's in wax all by myself.",
          "“Don't make a fuss,” he wires me. From San Francisco! Don't make a fuss. I made a fuss. The whole block came.",
          "That Flanagan girl wrote my Salvatore every week he was gone. Every week! Irish, yes. But every week.",
          "My strawberry-rhubarb is in the pie contest. I don't care if I win. I care if Mildred Hatch's lemon meringue loses.",
        ] },
      { first: 'Sal', nick: 'Sal Jr.', age: 24, sex: 'M', role: 'soldier', outfit: 'soldier', tags: ['veteran'], look: lk(SK.olive, HC.black, FC.plain, HS.buzz),
        bio: "Private First Class Salvatore Castellano Jr., 24, 7th Infantry Division. Home from Korea since Tuesday on the 4:52 from Boston — the last of the fourteen Juniper Bay boys who served there to come home, and all fourteen did. In the fourth grade he planted the third maple from the corner on Elm Street, after the '38 hurricane took the elms. It is taller than he is now. He doesn't say much about the war, and nobody makes him.",
        lines: [
          "It's quiet here. I forgot how quiet.",
          "Ma keeps feeding me like I'm still on the line.",
          "The harbor looks smaller. Or I got bigger. One of the two.",
          "I planted a maple on Elm Street in '39 — fourth grade, after the hurricane. Went and looked at it Wednesday. It made it. So did I.",
          "Dottie Flanagan wrote me every week. Fifty-some letters. I've got them all in a cigar box. ...Don't tell her I said so.",
          "There was a hill over there with a funny name. That's all I'm going to say about it today. Tell me what I missed here.",
        ] },
      { first: 'Maria', age: 19, sex: 'F', job: { building: 'Castellano Fish Market', role: 'fishmonger' }, look: lk(SK.olive, HC.black, FC.lashes, HS.long),
        bio: "Maria Castellano, 19. Works the scale at her Uncle Vinnie's fish market and wants to be a nurse — Theresa Duffy at St. Luke's is helping with her application. A bridesmaid at the Novak wedding this afternoon; she cried at the dress fitting because her brother was home. Best friends with Dottie Flanagan since the first grade, which is how Dottie got Sal's address.",
        lines: [
          "He's been home four days and I still keep crying. Over nothing! Over the toast!",
          "I gave Dottie Flanagan his address. Fourteen months of letters. You're welcome, Dottie.",
          "Nurse Duffy says St. Luke's might take me in the spring class. Pop says a Castellano should smell like fish, not ether. He'll come around.",
          "Bridesmaid at two, pink taffeta. Mrs. Silva says mine fits fine. I cried at the fitting anyway.",
        ] },
      { first: 'Lucia', age: 82, sex: 'F', title: 'Nonna', look: lk(SK.olive, HC.white, FC.old, HS.updo),
        bio: "Lucia Castellano, 82 — Nonna. Married Giuseppe's son Calogero in Sciacca in 1894, the year the old man sailed for America with his dory, and followed in 1898 with little Salvatore on her hip. She has seen the town go from gaslight to television and does not entirely approve of either.",
        lines: [
          "Bello... bello. My grandson, home.",
          "In Sciacca the sea is blue like this. Only warmer. And the fish, smaller.",
          "When I came in 1898 there was no trolley, no electric light on the wharf. Now my great-grandchildren will have television. Madonna mia.",
          "I prayed to San Calogero every day for fourteen months. He brought my Salvatore home. Father Garrity helped too, a little.",
          "You are too thin. Come tonight. Rosa makes the caponata the way I taught her. Almost.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Novaks (the wedding)
  {
    surname: 'Novak', home: { special: 'wedding_family' },
    members: [
      { first: 'Casimir', age: 48, sex: 'M', look: lk(SK.fair, HC.brown, FC.mustache, HS.part),
        bio: "Casimir Novak, 48, foreman on the packing floor at Harbor Canning Co. Came from Poland at three, in 1908. At 29 he stood on the City Hall steps for nineteen days in the July heat of the 1934 Cannery Strike and won the union a nickel an hour; there is a photograph of him in the Local 219 hall with “He was right” pencilled underneath. This afternoon he walks his daughter Helen down the aisle at St. Brigid's, and he is more frightened than he was in '34.",
        lines: [
          "Nineteen days we stood on those steps in '34. A nickel an hour. Worth every one of them.",
          "My Helen. Married. Where did the time go? I blinked, and she's keeping the cannery's books.",
          "Nick Papadakis's father brought us coffee on those steps, free, every morning. The cannery never forgave him. We never forgot.",
          "Birds Eye makes frozen fish sticks now. Mark my words, that's what comes after the tin can. I'm taking names for the winter pack Monday all the same.",
          "They asked to borrow my union button from '34 for the time capsule. Borrow! For a hundred years. I said yes.",
          "My brother Joe should be walking in behind us today. He's on the honor roll at City Hall. Helen has his laugh.",
        ] },
      { first: 'Stella', age: 46, sex: 'F', look: lk(SK.fair, HC.blonde, FC.glassesLipstick, HS.updo),
        bio: "Stella Novak, née Zielinski, 46. Sewed Helen's wedding gown herself over four months of evenings, with every one of the 212 seed pearls stitched by hand and counted twice. In '34 she made four hundred sandwiches for the men on the City Hall steps in her mother's kitchen. Has changed her mind about her hat four times, and has told Nora Brennan: no yellow corsage.",
        lines: [
          "Two hundred and twelve seed pearls. I counted twice. Miss Whitcomb says two hundred and twelve souls founded this town. I didn't plan it. God did.",
          "In '34 I made four hundred sandwiches for the men on the steps. Now I'm making a wedding. It's the same, really. You feed people and you hope.",
          "Casimir cried at the last fitting. Don't let him tell you otherwise.",
          "Nora Brennan wants a yellow corsage. Yellow! At my daughter's wedding. We have agreed not to discuss it. We discuss it every day.",
          "Sto lat, sto lat! That's what we'll sing at the reception. A hundred years — like the town.",
        ] },
      { first: 'Helen', age: 22, sex: 'F', role: 'bride', outfit: 'bride', look: lk(SK.fair, HC.blonde, FC.lashes, HS.curly),
        bio: "Helen Novak, 22, bookkeeper at Harbor Canning Co., marries Robert Brennan at St. Brigid's at two o'clock, Father Garrity officiating. Something old: Babcia's rosary in the bouquet. Something borrowed: Aunt Zofia's veil, from Chicopee, 1924. Something blue: her brother Walter is not to know.",
        lines: [
          "I'm not nervous. I'm not. Am I?",
          "Robert set our announcement in type himself. Nine times he checked it. I love a careful man.",
          "Two hundred and twelve pearls. Mother sewed every one. I'm afraid to sit down.",
          "Carol Kaminski's having her baby today and I'm having my wedding. Rita Wojcik doesn't know which way to run.",
          "In my letter for 2053 I wrote our names and the date and “they were very happy.” I'm going to make it true.",
        ] },
      { first: 'Walter', age: 17, sex: 'M', look: lk(SK.fair, HC.blonde, FC.plain, HS.short),
        bio: "Walter Novak, 17. Senior, wide receiver for the Mariners (they open against Gloucester next Friday), and reluctant usher at his sister's wedding, under strict written instructions from his mother. Also, though nobody is supposed to know it, sweet on Connie Ashby, the Congregational minister's daughter. They meet at table six in the Carnegie Library, and Miss Mayhew has not said one word to anybody.",
        lines: [
          "This collar is killing me. Ma wrote it down: do NOT take off the collar until after the photographs.",
          "Bride's side on the left, right arm to the ladies, do not run, and Cousin Stefan is not to be seated near the punch. I've got it on a card.",
          "If anybody asks, I was at the library Tuesday. And Thursday. Miss Mayhew will back me up.",
          "St. Brigid's and First Congregational are a block apart. A block! Some people act like it's the Atlantic Ocean.",
          "Pa stood on the City Hall steps for nineteen days in '34. Tonight I'm going to ask a girl to dance on the square. It takes nerve too.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Moreaus (Susie is seven)
  {
    surname: 'Moreau', home: { special: 'birthday' }, homeName: 'Moreau Residence — 14 Maple Street',
    members: [
      { first: 'Henri', age: 36, sex: 'M', role: 'clerk', look: lk(SK.light, HC.dark, FC.smile, HS.part),
        bio: "Henri Moreau, 36, window clerk at the post office. Came down from Trois-Rivières, Québec, at nineteen in 1936, found work sorting mail, and married Claire Beaumont, whose father sells shoes on Canal Street. His parents still write from Québec and come down on the train every Christmas. Blows up balloons with alarming skill and owns a Brownie camera he is very serious about.",
        lines: [
          "Seven candles. Seven! I remember when she fit in a bread basket.",
          "Musical chairs at half past two, pin the tail at three, cake at half past three. I have been told the rules are to be enforced. By me.",
          "Grand-maman and Grand-papa sent a card from Trois-Rivières with a dollar in it. Susie wants to frame the dollar.",
          "Mr. Lowell says my Brownie is a toy. Well, the toy got Susie blowing out the candles last year, and he wasn't invited.",
          "Susie's drawing of the family won first prize at the Maple Street School art show. It has a dog in it. We don't have a dog. Art is art.",
        ] },
      { first: 'Claire', age: 33, sex: 'F', look: lk(SK.light, HC.brown, FC.lipstick, HS.bob),
        bio: "Claire Moreau, née Beaumont, 33. Baked the birthday cake at midnight and iced it at dawn. Has a schedule clipped behind the invitation on the icebox — 2:00 guests, 2:30 musical chairs, 3:00 pin the tail, 3:30 CAKE, 4:15 presents, and nobody cries. Her pumpkin chiffon pie is in the contest, which she entered before remembering what day it was.",
        lines: [
          "Musical chairs at half past two, cake at half past three, and nobody cries. That's the plan.",
          "Papa brought Susie patent-leather Mary Janes. She slept in them. SLEPT in them.",
          "I entered a pumpkin chiffon in the pie contest. On my daughter's birthday. What was I thinking? I wasn't. That's what.",
          "Paul has been under the table since breakfast. He says he's a submarine.",
          "Ten children coming. Half of them will have Miss Lee for third grade. They'll behave for her. For me? We'll see.",
        ] },
      { first: 'Susie', age: 7, sex: 'F', tags: ['birthday'], look: lk(SK.light, HC.brown, FC.rosy, HS.long),
        bio: "Susie Moreau. Seven years old today! Has a fresh pencil line on the kitchen door frame to prove it.",
        lines: [
          "I'm SEVEN!",
          "I wished for a pony. I can't tell you, or it won't come true. Oh.",
          "Grandpapa gave me shiny shoes. I can see my face in them. Look! Look!",
          "My picture won first prize! It's got a dog in it. We don't have a dog. YET.",
          "Paul ate part of a candle. Just a little bit.",
        ] },
      { first: 'Paul', age: 4, sex: 'M', look: lk(SK.light, HC.brown, FC.rosy, HS.short),
        bio: "Paul Moreau, four, currently under the table.",
        lines: [
          "Is it cake time? Is it cake time now?",
          "I'm a submarine. Glub glub.",
          "Susie's SEVEN. I'm four. Four is almost seven.",
          "Did you see the fire truck? It goes WHEEE-OOO!",
        ] },
      { first: 'Émile', last: 'Beaumont', age: 63, sex: 'M', title: 'Mr.', job: { building: 'Beaumont Shoes', role: 'salesman' }, look: lk(SK.light, HC.gray, FC.glassesMustache, HS.part),
        bio: "Émile Beaumont, 63, of Beaumont Shoes on Canal Street, Claire Moreau's father. Came down from Sherbrooke, Québec, in 1921 by way of the Lowell mills. A widower since '47, he lives with his daughter's family and fits every child's foot in Juniper Bay with the solemn care he'd give a bishop's — and will tell you your arches are falling.",
        lines: [
          "Susie slept in the Mary Janes. Claire is furious. I have never been prouder.",
          "Sherbrooke, then the mills at Lowell, then here in 1921. At the mills I made the thread. Here I make the shoes. That's progress.",
          "A child's foot grows a size every six months. I tell the mothers. The mothers say I'm a salesman. I am. I'm also right.",
          "The Halloran boy looks at his toes in my X-ray machine three times a week. His mother has asked me to stop. I have not been able to say no to him.",
          "Armand Tremblay and I argue about the Canadiens in French every Sunday after Mass. The parish thinks we are praying.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ Whitcomb House (the historian)
  {
    surname: 'Whitcomb', home: { special: 'historian' }, homeName: 'Whitcomb House',
    members: [
      { first: 'Augusta', age: 81, sex: 'F', title: 'Miss', look: lk(SK.fair, HC.white, FC.glasses, HS.updo), tags: ['historian'],
        bio: "Miss Augusta Whitcomb, 81, great-granddaughter of Captain Elias Whitcomb, who brought the schooner JUNIPER into this cove out of the October gale of 1851 and swore he would come back. President of the Historical Society for thirty years and author of “Juniper Bay: A Centennial History” ($2.50 at Pike & Daughter; she will know if you have not read it). At half past five she seals the time capsule on Founders Square. There are no Whitcomb men left: her nephew Richard fell at Seicheprey in 1918, and young Elias the Third in 1944.",
        lines: [
          "My great-grandfather sheltered the JUNIPER in this cove in '51 and swore he'd come back. He did.",
          "The time capsule goes in the ground at half past five. My letter to 2053 is in it. I told them to be kind.",
          "Look for the cornerstones downtown — 1903, 1904, 1905. Everything after the fire.",
          "The widows of the MARY ELLEN raised the stone on the quay. Go and read the names. Somebody should, every day.",
          "Richard in 1918. Elias in 1944. There are no more Whitcomb men. There's me, and there's the town. The town will have to do.",
          "Clara Fairweather and I were girls at the Academy together. She remembers everything, which is a great nuisance to Mr. Thorne.",
          "One white rose on the capsule. That's all I asked the Bower girls for. One. They are not speaking to each other over it.",
        ] },
      { first: 'Delia', last: 'Coffey', age: 70, sex: 'F', title: 'Mrs.', look: lk(SK.fair, HC.gray, FC.old, HS.bob),
        bio: "Mrs. Delia Coffey, 70, housekeeper at Whitcomb House for forty-four years. Came from Galway in 1900 “for two years, to send money home.” Knows where every photograph in the Historical Society files is kept, and most of the family secrets besides. Has read all eleven drafts of Miss Augusta's letter to 2053.",
        lines: [
          "Forty-four years I've kept this house. Miss Augusta says I'm the only one who can find anything, which is true.",
          "She's rewritten her letter for the capsule eleven times. I've read every one. The eighth was the best. Don't tell her.",
          "Galway, 1900. I came for two years to send money home. That was fifty-three years ago.",
          "Don't let her carry that capsule herself. Eighty-one, and she thinks she's the Captain.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Mayor
  {
    surname: 'Pemberton', home: { name: 'Pemberton House' },
    members: [
      { first: 'Walter', age: 61, sex: 'M', title: 'Mayor', role: 'mayor', formal: true, look: lk(SK.fair, HC.gray, FC.glasses, HS.part, { hat: 'hat_top', hatTint: '#1c1c20' }),
        bio: "Mayor Walter Pemberton, 61, in his third term. Old Yankee stock. Taught his letters by Miss Clara Fairweather in 1898, fitted for every suit he owns by Isaac Adler. His younger brother Arthur died of the influenza at Camp Devens in October 1918 and never got to France; his name is on the Great War board at City Hall. His Centennial address was eleven pages. His wife cut it to six in green ink.",
        lines: [
          "Fellow citizens— oh, sorry, just practicing.",
          "A hundred years. Imagine what they'll think of us in 2053.",
          "Eleven pages. Eleanor cut it to six. She cut the part about the municipal water department. That was my best part.",
          "Miss Fairweather taught me to read in 1898. She still corrects my grammar in the letters column. She's usually right.",
          "My brother Arthur died at Camp Devens in '18, of the influenza. Never saw France. I'll say his name tonight, to myself, when I say the others.",
          "The trolley stays as long as I'm mayor. Buses are fine for Worcester.",
        ] },
      { first: 'Eleanor', age: 58, sex: 'F', formal: true, look: lk(SK.fair, HC.salt, FC.glassesLipstick, HS.updo),
        bio: "Eleanor Pemberton, 58, chairman of the Centennial Committee. Has not slept since June. Arranged the fair, the band, the bunting, the fireworks barge, the capsule, and the Mayor's speech (by removing five pages of it). A judge of the pie contest this afternoon, a position she accepted under protest and now regrets.",
        lines: [
          "If one more person asks me about the fireworks permit...",
          "Sixty-one pies. Nine of them “Grandmother's recipe.” I'm judging with Father Garrity and Nick Papadakis. I have to live here afterward.",
          "I cut the water department from Walter's speech. Nobody in 2053 wants to hear about the water department. Nobody NOW wants to hear about it.",
          "Madame Gould made me something for the podium. “Not too tall — the Mayor is sensitive.” He is.",
          "The fireworks go up from a barge at nine. All vessels two hundred yards clear. I made Mr. Hallett put it on the harbor master's board in capitals.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ Mrs. Hatch and Admiral
  {
    surname: 'Hatch', home: { special: 'cat' },
    members: [
      { first: 'Mildred', age: 72, sex: 'F', title: 'Mrs.', look: lk(SK.fair, HC.white, FC.glasses, HS.curly),
        bio: "Mrs. Mildred Hatch, 72, widow of Captain Horace Hatch, master of the coastal steamer JUNIPER QUEEN, Boston to Portland, 1911–1938, who stood her off Gannet Ledge through the '38 hurricane with ninety passengers aboard and brought every one of them in. Lives in the house his grandfather built in 1884. Owner of Admiral, a large gray tomcat of poor judgment and excellent appetite. Please do not feed him.",
        lines: [
          "Admiral! Admiral, you come down this instant!",
          "Horace named him. Horace would.",
          "Four times since Easter. Joe Brennan says the next time they're sending me a bill. I'll send him a lemon meringue. Two can play.",
          "Please don't feed him. He tells everybody he's starving. He is not starving. Look at him.",
          "Horace tapped that barometer every morning for forty years. So do I. This morning it said FAIR. He'd have liked that, for the fireworks.",
          "Hazel Crane says the cat is a disgrace to the neighborhood. Hazel Crane can mind her own neighborhood.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Kaminskis (the baby)
  {
    surname: 'Kaminski', home: { family: 'Kaminski' },
    members: [
      { first: 'Stan', age: 27, sex: 'M', look: lk(SK.fair, HC.brown, FC.plain, HS.short),
        bio: "Stanley Kaminski, 27, lineman for the telephone company — climbed every pole on Church Street in the ice storm of '51. His wife Carol's pains started at 11:20 last night; he left a note on the kitchen table in capital letters, took the suitcase, and forgot his hat. He has been pacing the waiting room at St. Luke's ever since and has asked the nurses for news roughly every four minutes.",
        lines: [
          "Any minute now. Any minute.",
          "Dr. Pike says first babies take their time. How much time? He didn't say how much time.",
          "If it's a boy, Joseph, for my brother. He's on the honor roll at City Hall. If it's a girl, Carol says Rose, after her grandmother. I say whatever Carol says.",
          "Opal Fisk already knitted a sweater. Yellow. She says she's hedging.",
          "I climbed every pole on Church Street in the '51 ice storm and I wasn't scared once. I'm scared now.",
        ] },
      { first: 'Carol', age: 25, sex: 'F', look: lk(SK.fair, HC.blonde, FC.lipstick, HS.curly),
        bio: "Carol Kaminski, née Wojcik, 25, formerly of the labeling line at Harbor Canning. Currently at St. Luke's Hospital, having a baby, and in no mood for visitors — though she would like someone to tell her mother.",
        lines: [
          "Tell Stan to sit DOWN.",
          "Nurse Coleman says I'm doing fine. Nurse Coleman is a saint.",
          "Rita's at the wedding? Good. Somebody in this family should be having fun today.",
          "If it's a girl, Rose. After Grandma Wojcik. She came over in 1908 with a feather bed and a crucifix and nothing else.",
        ] },
      { first: 'Danny', age: 17, sex: 'M', job: { building: "Kowalski's Market", role: 'stock boy' }, look: lk(SK.fair, HC.dark, FC.smile, HS.part),
        bio: "Daniel Kaminski, 17, Stan's kid brother, who has lived with Stan and Carol since their mother moved in with their sister in Worcester. Stock boy at Kowalski's Market, second-string halfback, and — according to a certain diary — the “D.K.” with whom Peggy Halloran is not going to the sock hop.",
        lines: [
          "Stan left me a note: FEED THE CAT. TELL MY MOTHER. In capitals. I fed the cat. I told Ma. Now I'm stocking soup.",
          "I'm going to the sock hop. Alone. Everybody goes alone. Then you just — end up somewhere. Near somebody.",
          "Mr. Kowalski says a stock boy who whistles is a stock boy who's thinking about a girl. I don't whistle. Much.",
          "My brother Joe would've been an uncle today. He's on the board at City Hall. Stan doesn't talk about it. I think about it every time I see the flag.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Parsonage
  {
    surname: 'Ashby', home: { name: 'The Parsonage' },
    members: [
      { first: 'Theodore', age: 52, sex: 'M', title: 'Reverend', role: 'clergy', outfit: 'clergy', job: { building: 'First Congregational Church', role: 'minister' }, look: lk(SK.fair, HC.salt, FC.glasses, HS.part),
        bio: "The Reverend Theodore Ashby, 52, minister of First Congregational — the oldest congregation in town, gathered in 1853, in the present meetinghouse since 1871. A Maine man, a patient fisherman, and a great friend of Father Garrity, with whom he plays checkers every Tuesday in booth four of the Harbor Light Diner, a block from both their churches. Tomorrow's Centennial sermon is on Psalm 107.",
        lines: [
          "The meetinghouse was raised in 1871 by fifty men in one day. We still have the ledger. Deacon Pike struck his thumb.",
          "Father Garrity and I play checkers at the diner on Tuesdays. He cheats. I pray for him. We're both content.",
          "Tomorrow: Psalm 107. “They that go down to the sea in ships, that do business in great waters.” Where else could a man preach it?",
          "Leonard Pruitt has played that organ for thirty years. I've been here twelve. We both know who's in charge.",
          "Constance has been spending a great deal of time at the library lately. I'm delighted. Miss Mayhew says she's very studious.",
        ] },
      { first: 'Margaret', age: 50, sex: 'F', title: 'Mrs.', look: lk(SK.fair, HC.brown, FC.glassesLipstick, HS.bob),
        bio: "Margaret Ashby, 50, the minister's wife and president of the Ladies' Auxiliary, which is running the pie contest from a tent on the square. She has sixty-one pies, nine claims of “Grandmother's recipe,” and two women — Irene Halloran and Loretta Quimby — who have not spoken since the Truman administration.",
        lines: [
          "Sixty-one pies. The Auxiliary counted them twice. Nine say “Grandmother's recipe.” Several grandmothers are going to be very surprised.",
          "Irene Halloran and Loretta Quimby. I put the pie tables twelve feet apart. I measured. Then Loretta withdrew anyway.",
          "Connie's at the library again. Such a good girl. Theodore thinks it's the Brontës. I have my own ideas.",
          "The Auxiliary rolled bandages at the Elks Lodge all through the war. Four years. I still dream in gauze.",
        ] },
      { first: 'Constance', age: 17, sex: 'F', look: lk(SK.fair, HC.light, FC.freckles, HS.long),
        bio: "Constance “Connie” Ashby, 17, the minister's daughter. Top of her class, sings alto in the choir, and has spent an extraordinary number of afternoons this fall at table six of the Carnegie Library — always, by coincidence, at the same table as Walter Novak of St. Brigid's.",
        lines: [
          "Father thinks I'm at the library. I am at the library. Mostly.",
          "Walter Novak? From St. Brigid's? I hardly know him. He's very good at... catching things.",
          "Mr. Pruitt says the altos drag. Altos don't drag. Altos are thoughtful.",
          "Miss Mayhew hasn't said a word to anybody. She just hands me Jane Austen and smiles.",
          "In 2053 I hope a Congregational girl and a Catholic boy can dance on Founders Square and nobody says one word about it.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Kowalskis (upstairs from the market)
  {
    surname: 'Kowalski', home: { name: "Kowalski's Market" },
    members: [
      { first: 'Walter', age: 67, sex: 'M', role: 'shopkeeper', job: { building: "Kowalski's Market", role: 'butcher' }, look: lk(SK.fair, HC.white, FC.mustache, HS.bald),
        bio: "Walter Kowalski, 67, came from near Kraków in 1908 with the first Polish families to work the cannery, and opened Kowalski's Market on Mill Street in 1915 with his savings and a borrowed scale. In July of 1934 he drew a line through every striker's debt in the credit ledger and wrote “Zapłacone. Wszystko.” — Paid. All of it. Nobody had paid anything. Handed the store to his son Ted in '48, but still makes the kielbasa from his mother's recipe.",
        lines: [
          "1908 I came, with Casimir Novak's family on the same boat. Two families, one trunk of kiełbasa. We were very popular on that boat.",
          "In '34 the strikers owed me four hundred dollars. I wrote in the book: paid, all of it. What was I going to do, eat the ledger?",
          "Now in Gloucester they have a “supermarket.” You push a cart. Nobody knows your name. What is the point of that?",
          "My brother Stanisław went to France with the Yankee Division. He'd been an American nine years. He was proud of it. He's on the board at City Hall.",
          "The committee says my kiełbasa is not a pie. I have never claimed it is a pie. I only said it would win.",
        ] },
      { first: 'Wanda', age: 64, sex: 'F', look: lk(SK.fair, HC.gray, FC.old, HS.updo),
        bio: "Wanda Kowalski, 64, makes the pierogi sold at the market on Fridays and at the fair stall today — “Pinch them shut TIGHT or they open in the pot, and Babcia will know.” Lost her younger son Walter in the war; her older son Ted came home from Bastogne with a Silver Star he keeps in a drawer and has never mentioned.",
        lines: [
          "Pierogi! Potato and cheese, sauerkraut, and plum for the children. Five cents, or two for the Mayor.",
          "Stella Novak's pearls — I held the lamp for her the last week. My eyes aren't what they were but my hands are steady.",
          "My Teddy got a Silver Star at Bastogne. It's in his dresser drawer. He doesn't know I know where he put it.",
          "My Walter is on the honor roll. My Teddy came home. I light one candle for each, every Sunday. One for sorrow, one for thanks.",
        ] },
      { first: 'Ted', age: 36, sex: 'M', role: 'shopkeeper', job: { building: "Kowalski's Market", role: 'grocer' }, look: lk(SK.fair, HC.brown, FC.plain, HS.short),
        bio: "Tadeusz “Ted” Kowalski, 36, runs Kowalski's Market. Was at Bastogne with the 101st Airborne that winter; came home with a Silver Star he keeps in a drawer and has never mentioned to a living soul. Talks about kielbasa, the Red Sox and the weather. Not the war. Never the war. Bowls a 210 on Thursdays at Harbor Lanes and never smiles doing it.",
        lines: [
          "The war? Ah, it was cold. Say — you want some kiełbasa? Pop smoked it himself.",
          "Ma thinks I don't know she found the medal. I know. She knows I know. That's a Polish family for you.",
          "Vic DeLuca tells war stories at the Signal Lamp every night. Somebody's got to. Better him than me.",
          "Supermarket in Gloucester? Let 'em. They don't know Mrs. Hatch buys salmon for a cat who isn't supposed to eat.",
          "I like it quiet. A store's a quiet thing, mornings. You put the apples out, you sweep. Nobody yells.",
          "Red Sox are fourth again. Williams is back, though. Next year. It's always next year in this town.",
        ] },
      { first: 'Frances', age: 33, sex: 'F', look: lk(SK.fair, HC.auburn, FC.lipstick, HS.bob),
        bio: "Frances Kowalski, née Crowell, 33 — Agnes Crowell's daughter, so George Crowell, killed at Anzio, was her brother. A Yankee girl from the old quarry family who married a Polish grocer in 1947 and learned to make pierogi to her mother-in-law's grudging satisfaction. Works the register and knows every customer's credit by heart.",
        lines: [
          "Ted won't talk about the war and Ma won't stop thinking about it. I'm in the middle, ringing up soup.",
          "My brother George was killed at Anzio. Theresa Duffy was a nurse there. She wrote Ma the kindest letter. We read it every Memorial Day.",
          "A Crowell marrying a Kowalski! My grandmother said the quarry would fall into the sea. The quarry is fine.",
          "Ninety-three cents for a pound of coffee. I know every price in this store, and every family's credit, and I never say either one out loud.",
        ] },
    ],
  },
  // ------------------------------------------------------------------ the Silvas (upstairs from the dress shop)
  {
    surname: 'Silva', home: { name: 'Silva Dress Shop' },
    members: [
      { first: 'Maria', age: 52, sex: 'F', title: 'Mrs.', role: 'shopkeeper', job: { building: 'Silva Dress Shop', role: 'saleslady' }, look: lk(SK.tan, HC.dark, FC.glassesLipstick, HS.updo),
        bio: "Maria Silva, 52, came from São Miguel in the Azores in 1923 and sewed in her kitchen for ten years before she could afford a window on Market Street. Today she dressed four bridesmaids in pink taffeta for the Novak wedding — Helen's cousin Dorota, Peggy Halloran, the Brennan girl and Maria Castellano — and pressed the bride's gown, which she will tell you she did not otherwise touch, because it was perfect.",
        lines: [
          "Four bridesmaids, pink taffeta. One let out an inch — I don't say which. One cried at the fitting. That was Maria Castellano. Her brother is home.",
          "Stella Novak sewed the gown herself. Two hundred and twelve pearls. I only pressed it. It is perfect. I don't say that often.",
          "The nuns on São Miguel taught me to sew. They could hem a sail and a christening gown the same afternoon.",
          "Harlow's sells dresses off a rack now. Off a rack! A dress should know the woman.",
          "My son Manny's girl was born the fourteenth. Theresa. Now there are two Maria Silvas in the family and a baby to spoil. We call his wife Maria-the-younger. She doesn't love it.",
        ] },
      { first: 'José', nick: 'Joe', age: 55, sex: 'M', role: 'fisherman', outfit: 'fisherman', job: { building: 'Juniper Bay Waterfront', role: 'net mender' }, look: lk(SK.tan, HC.salt, FC.mustache, HS.short),
        bio: "José “Joe” Silva, 55, skipper of the dragger SANTA MARIA, which lands at Pier 3 with the Castellano boats. His older brother António came first, went to France with the Yankee Division and was killed in the Argonne in October 1918; Joe came over from São Miguel the next year, “to take his place,” his mother said. Carries the statue at the Blessing of the Fleet every June. Mends nets on Saturday mornings, and lets his knees complain.",
        lines: [
          "Fleet came in at six. Good haddock, better mackerel, and a lobster who argued the whole way in.",
          "My brother António is on the 1918 board at City Hall. I came the next year. My mother said: go, take his place. Thirty-four years I've been trying.",
          "Every June Father Garrity blesses the fleet. Since 1891, when the first Azoreans came. I carry the statue. My knees complain. I carry it.",
          "Manuel Furtado was my wife's cousin. The '38 storm. Bea keeps his oilskins on a hook at the Clam Shack. So do I, in my head.",
          "Fog by morning. You can smell it. Tell the fireworks men to hurry.",
        ] },
      { first: 'Filomena', nick: 'Mena', age: 21, sex: 'F', job: { building: 'Silva Dress Shop', role: 'seamstress' }, look: lk(SK.tan, HC.black, FC.lashes, HS.long),
        bio: "Filomena “Mena” Silva, 21, the fastest needle on Market Street. Saves every Saturday's pay for an electric sewing machine of her own from Tremblay Furniture, a dollar a week on layaway. Going to the street dance with Rita Wojcik and Josie DeLuca: three girls from the waterfront, and the boys of Juniper Bay have been warned.",
        lines: [
          "Four bridesmaids' dresses by Friday night. My fingers still hurt. Worth it — wait till you see them come down the aisle.",
          "Mr. Tremblay says a dollar a week and the electric machine is mine by Easter. I've already named it. Don't ask.",
          "Josie DeLuca and Rita Wojcik and me — we're going to the street dance together. Safety in numbers. And better dancing.",
          "Ma says “straighter.” Ma always says “straighter.” Someday I'll sew a seam so straight she'll have nothing to say.",
        ] },
    ],
  },
];

export const NOTABLES = [
  // ------------------------------------------------------------------ the Freemans (barber shop, choir, the Blue Lantern)
  { first: 'Marcus', last: 'Freeman', age: 45, sex: 'M', role: 'barber', outfit: 'barber', job: { building: "Freeman's Barber Shop", role: 'barber' }, look: lk(SK.dark, HC.black, FC.mustache, HS.short),
    bio: "Marcus Freeman, 45, proprietor of Freeman's Barber Shop on Market Street. His father Samuel came north from Virginia in 1919 and opened the shop in 1921 with one chair and a secondhand mirror; there are two chairs now and the same mirror. His younger brother Samuel Jr. is on the World War II honor roll at City Hall. Married to Ruth, the choir's soloist. Knows everything that happens in town by Tuesday, and repeats none of it.",
    lines: [
      "Pop opened this shop in '21 with one chair and a secondhand mirror. That's the mirror. Still tells the truth.",
      "Ruth's singing the solo tomorrow. Practice is at four — go listen, it'll set you right.",
      "Shave and a haircut? Two bits. Well — seventy-five cents. Some things change.",
      "Everybody tells the barber everything. The trick is, the barber tells nobody. That's why we're still open.",
      "I cut Sal Castellano Jr.'s hair Wednesday. Didn't say a word the whole time, either of us. Best conversation I had all week.",
      "My brother Sammy's name is on the board at City Hall, the new one. My boy's named for him and for Pop both. That's a lot of name for a fifteen-year-old to carry. He carries it fine.",
    ] },
  { first: 'Ruth', last: 'Freeman', age: 42, sex: 'F', role: 'choir', look: lk(SK.dark, HC.black, FC.lipstick, HS.updo, { socks: SK.dark }), tags: ['choir', 'soloist'],
    bio: "Ruth Freeman, 42, soloist of the First Congregational choir for fifteen years and the reason half the town comes to the Christmas service. Born in Juniper Bay; her grandmother came up from Richmond in 1890 to cook at the Whitcomb Hotel. Tomorrow she sings “Now Thank We All Our God” for the Centennial service. Her sweet potato pie is in the contest, and she would like it known that she does not care who wins.",
    lines: [
      "We're singing “Now Thank We All Our God” for the centennial. Mr. Pruitt says my high note is “adequate.” High praise.",
      "My grandmother came up from Richmond in 1890 to cook at the Whitcomb Hotel. She said the fog made her homesick for nothing at all.",
      "Mr. Pruitt and I have fought over tempo for fifteen years. He's wrong, and he plays beautifully.",
      "Sammy practices his horn in the cellar. The furnace has never sounded better.",
      "My sweet potato pie is up against eight kinds of apple. I don't care who wins. I care very much who wins.",
      "In my letter for 2053 I copied out the words to “Blest Be the Tie That Binds.” It's the only thing I know for certain will still be true.",
    ] },
  { first: 'Samuel', last: 'Freeman', age: 66, sex: 'M', title: 'Mr.', formal: true, look: lk(SK.dark, HC.white, FC.glassesMustache, HS.short),
    bio: "Samuel Freeman, 66, founder of Freeman's Barber Shop. Born in Norfolk, Virginia; unloaded ships at Saint-Nazaire in France with an Army stevedore regiment in 1918; came north in 1919 because a ship's mate told him Juniper Bay had the prettiest harbor on the coast. Opened his shop in 1921. Lost his younger son in the Second War. Retired in '46, but sits in the chair by the window every day, reading the Courier with a pencil and correcting it for Miss Lowell.",
    lines: [
      "In 1919 a ship's mate told me Juniper Bay was the prettiest harbor on the coast. First man I ever met who didn't lie about a harbor.",
      "My first customer was a Portuguese fisherman with no English, and I had no Portuguese. Best haircut I ever gave. He came back every two weeks for thirty years.",
      "In '21 there were some on Market Street who didn't care to see my name over a door. Isaac Adler lent me his good shears till mine came from Boston. I don't forget that.",
      "France, 1918. Unloaded ships at Saint-Nazaire for a year. Never saw the front. Saw plenty.",
      "I mark up the Courier every morning and walk it over to Miss Lowell. Three errors Tuesday. She says I'm her best proofreader. I say she needs one.",
      "My boy Samuel Jr. didn't come home from the Pacific. His name's on the board. I go and read it Sundays after church, and then I come here and cut hair. That's how you go on.",
    ] },
  { first: 'Sammy', last: 'Freeman', age: 15, sex: 'M', job: { building: "Freeman's Barber Shop", role: 'shoeshine' }, look: lk(SK.dark, HC.black, FC.smile, HS.buzz),
    bio: "Samuel “Sammy” Freeman, 15, named for his grandfather and for his uncle on the honor roll. Sophomore, second trumpet in the high school band, and shoeshine boy at his father's shop on Saturdays. Paying off a secondhand cornet from Bishop Music Co. at fifty cents a week. Wants more than anything to sit in with his cousin Earl's quartet at the Blue Lantern.",
    lines: [
      "Shine, mister? Ten cents, and I'll tell you the Red Sox score for free.",
      "Cousin Earl says if I can play “Stardust” clean, I can sit in. Someday. Not tonight. Pop says not tonight.",
      "Mr. Bishop let me have the cornet for fifty cents a week. I've got eleven weeks to go.",
      "Campanella hit forty-one homers this year. Forty-one! For a catcher! The Dodgers are finally going to take the Yankees, you watch.",
      "Mr. Coleman says if I scuff his gym floor tonight he'll have my socks bronzed. With me in them.",
    ] },
  { first: 'Earl', last: 'Freeman', own: true, age: 39, sex: 'M', role: 'shopkeeper', formal: true, home: { name: 'The Blue Lantern' }, job: { building: 'The Blue Lantern', role: 'bandleader' }, look: lk(SK.deep, HC.black, FC.mustache, HS.part),
    bio: "Earl Freeman, 39, pianist, bandleader and owner of the Blue Lantern on Church Street; Marcus's cousin. Bought his first real piano at Bishop Music on time payments in 1937 — it took him four years — played Boston and New York, and came home in 1946 to make the Blue Lantern the only room between Boston and Portland where a musician passing through can sit in until two in the morning. The Earl Freeman Quartet plays the late set at nine, live on WJBY at eleven.",
    lines: [
      "Late set starts at nine. Bring someone you like.",
      "I played New York in '41. Came home anyway. New York's got everything but a harbor that knows your name.",
      "Tenor man tonight is up from Providence. Plays like he's got somewhere to be and no hurry at all to get there.",
      "Sammy's got it. Whatever it is, the boy's got it. But Marcus is right — school first. Music will wait. It waited for me.",
      "WJBY carries us live at eleven. Bill Ferris says keep it clean for the radio. I say, Bill, it's jazz — it's the cleanest thing there is.",
      "My first piano came from Bishop's, 1937, fifty cents a week, four years. Mr. Bishop never once came to collect. I brought it to him every Saturday anyway.",
    ] },
  // ------------------------------------------------------------------ the Papadakises (Harbor Light Diner)
  { first: 'Nick', last: 'Papadakis', age: 55, sex: 'M', role: 'cook', outfit: 'cook', job: { building: 'Harbor Light Diner', role: 'cook' }, look: lk(SK.olive, HC.salt, FC.mustache, HS.short),
    bio: "Nick Papadakis, 55, of the Harbor Light Diner. Came from Chios in 1920 with his father, who opened a lunch counter on Harbor Street in 1924. In the 1934 strike the old man poured free coffee for the men on the City Hall steps every morning; the cannery never forgave him, and the town never forgot. The dining car was installed the winter after the '38 hurricane. The Papadakises lost their son George in the war. A judge of the pie contest today, God help him.",
    lines: [
      "Chowder's on Friday. Pie is always.",
      "Pop served coffee to the strikers in '34, on the house. Cannery never forgave him. Town never forgot.",
      "The dining car came up on a flatbed in December of '38, with Harbor Street still drying out. We opened New Year's Day.",
      "They made me a pie judge. Nine apple pies that are all “Grandmother's recipe.” I'm Greek. I don't know any of these grandmothers.",
      "Father Garrity and the Reverend, Tuesdays, booth four, checkers. They argue theology and split the check to the penny.",
      "Lonnie Tobey gets his eggs free. Don't tell him I told you. He thinks Eleni forgets to charge him.",
    ] },
  { first: 'Eleni', last: 'Papadakis', age: 52, sex: 'F', role: 'waitress', outfit: 'waitress', job: { building: 'Harbor Light Diner', role: 'waitress' }, look: lk(SK.olive, HC.dark, FC.smile, HS.updo),
    bio: "Eleni Papadakis, 52, has worked the counter of the Harbor Light since 1938 and remembers the order of every regular in town — and most of their troubles. Tuesday afternoons she plays mahjong with Lily Lee, Esther Adler and Rosa Castellano, and wins. Her Dutch apple pie is entered in the contest her own husband is judging, which she considers his problem.",
    lines: [
      "Coffee, black, two sugars? I knew it.",
      "Tuesdays I play mahjong with Lily Lee and Esther Adler and Rosa Castellano. Lily taught us. Now we take her money.",
      "My Dutch apple is in the contest and Nick is a judge. If he votes for me, it's a scandal. If he doesn't, he sleeps in the diner.",
      "I don't forget to charge Lonnie Tobey. I just don't charge him. Different thing.",
      "On V-J Day we gave away every doughnut in the place and Nick climbed the bronze soldier with a flag. I have never been so embarrassed or so proud.",
    ] },
  { first: 'Sophia', last: 'Papadakis', age: 20, sex: 'F', role: 'waitress', outfit: 'waitress', job: { building: 'Harbor Light Diner', role: 'waitress' }, look: lk(SK.olive, HC.black, FC.lashes, HS.bob),
    bio: "Sophia Papadakis, 20, waitress at the Harbor Light on weekends and a sophomore at Boston University on weekdays, riding the 6:10 every morning. Wants to be a newspaperwoman; Ada Lowell lets her write up the church suppers for the Courier and has promised her the Centennial fireworks for Sunday's edition. Goddaughter of Gus Kouris, who still brings her licorice.",
    lines: [
      "Miss Lowell said I can write up the fireworks for the Sunday edition. My first real byline! Well — “S.P.” But still.",
      "The 6:10 to Boston every weekday. Mr. Lindqvist says I'm the only passenger who's never once been late. I'm the only passenger who's scared of him.",
      "Uncle Gus still brings me licorice. I'm twenty. I eat every piece.",
      "Pop says a newspaperwoman is no job for a Greek girl. Then he reads my church suppers out loud to the whole counter.",
    ] },
  // ------------------------------------------------------------------ the Lees (upstairs from the laundry)
  { first: 'Henry', last: 'Lee', age: 62, sex: 'M', role: 'shopkeeper', home: { name: "Lee's Hand Laundry" }, job: { building: "Lee's Hand Laundry", role: 'clerk' }, look: lk(SK.warm, HC.gray, FC.glasses, HS.short),
    bio: "Henry Lee, 62, of Lee's Hand Laundry on Market Street. His father, Lee Wing, came from Taishan and opened the laundry in 1911, the year the Carnegie Library opened — “a town with a free library is a good town,” he said. Henry still starches collars the way Captain Whitcomb's son liked them: heavy. Daughter Grace teaches third grade; son David is a radioman in the Navy, writing from Yokosuka.",
    lines: [
      "My father pressed shirts for Captain Whitcomb's son. Starch, heavy. He always said: heavy.",
      "David writes from Yokosuka. He says the sea is the same everywhere. His mother says come home anyway.",
      "My father opened the same year as the library. He said a town with a free library is a good town. He read every book in it about ships.",
      "The law in those days made it very hard for a Chinese man to come here at all. My father came anyway. Then he pressed the Mayor's shirts for twenty years. Life is funny.",
      "The Mayor's collars today, extra stiff. He will be turning his head a great deal at half past five.",
    ] },
  { first: 'Lily', last: 'Lee', age: 56, sex: 'F', title: 'Mrs.', job: { building: "Lee's Hand Laundry", role: 'presser' }, look: lk(SK.warm, HC.dark, FC.glassesLipstick, HS.bob),
    bio: "Lily Lee, 56, born on Tyler Street in Boston's Chinatown; married Henry in 1925 and considers Juniper Bay “the country” to this day. Taught half the women of Market Street to play mahjong and now loses to them every Tuesday. Writes to her son David every Sunday, three pages, with a clipping from the Courier.",
    lines: [
      "I was born in Boston. Tyler Street. To me this is still the country — too many trees, not enough noodles.",
      "I taught Eleni and Esther and Rosa to play mahjong. Now they take my money every Tuesday. This is what I get for being generous.",
      "Every Sunday I write David three pages and put in a clipping. This week: the centennial. Next week: probably the fireworks set fire to something.",
      "Grace is too busy to get married. Twenty-six! When I was twenty-six I had two children and a laundry.",
    ] },
  { first: 'Grace', last: 'Lee', age: 26, sex: 'F', title: 'Miss', role: 'clerk', look: lk(SK.warm, HC.black, FC.lipstick, HS.bob),
    bio: "Miss Grace Lee, 26, teaches third grade at the Maple Street School and has taught, or will teach, nearly every child at Susie Moreau's birthday party. She was eighteen on V-J Day and danced with half the Navy on Founders Square. Her brother David is on a destroyer out of Yokosuka. Her mother would like her married. She would like thirty-one children to spell “Massachusetts.”",
    lines: [
      "Susie Moreau's in my class next fall. She's already told me she's seven. Four times.",
      "On V-J Day I was eighteen and I danced with half the Navy on Founders Square. Mother still hasn't forgiven the other half.",
      "David's on a destroyer out of Yokosuka. He sends me postcards of Mount Fuji and asks about the Red Sox.",
      "I'm not getting married this year, Mother. I'm teaching thirty-one children to spell “Massachusetts.” That's commitment enough.",
      "Dora Vance's fourth grade wrote the letters for the time capsule. Mine drew pictures. Thirty-one lighthouses. They're all wonderful. Some of them are also ducks.",
    ] },
  // ------------------------------------------------------------------ the Adlers (upstairs from the tailor's)
  { first: 'Isaac', last: 'Adler', age: 70, sex: 'M', role: 'shopkeeper', formal: true, home: { name: 'Adler & Son, Tailors' }, job: { building: 'Adler & Son, Tailors', role: 'tailor' }, look: lk(SK.light, HC.white, FC.glasses, HS.bald),
    bio: "Isaac Adler, 70, came from Vilna in 1905 with a pair of shears and a thimble, and opened Adler & Son on Market Street in 1906. Has cut every suit in the Mayor's closet and still cuts every one by hand. His son Samuel does the fittings; Isaac does the arguing. His wife Esther has been asking him to close on Saturdays for forty-seven years.",
    lines: [
      "Forty-seven years, and every suit by hand. A machine? A machine doesn't know a man's shoulders.",
      "Esther says close on Shabbos like my father did in Vilna. Forty-seven years she's been saying. Forty-seven years I've been almost ready.",
      "Samuel Freeman needed shears in '21. I had shears. What's to tell? A barber with no shears is a man with a chair.",
      "The Mayor's suit for tonight — navy, double-breasted, a little room in the chest for the speech. He breathes big when he talks.",
      "For 2053 I wrote one line: “A suit should be made by a man who knows your name.” Let them argue.",
    ] },
  { first: 'Esther', last: 'Adler', age: 67, sex: 'F', title: 'Mrs.', look: lk(SK.light, HC.gray, FC.glassesLipstick, HS.updo),
    bio: "Esther Adler, 67, came from Vilna as a bride of nineteen in 1905. Keeps the books at Adler & Son and the Sabbath at home, and founded the Juniper Bay chapter of Hadassah in 1921. Plays mahjong on Tuesdays at the Harbor Light; plays to win.",
    lines: [
      "Every Friday night I light my mother's candlesticks — brass, from Vilna. They crossed the ocean in a pillowcase.",
      "Mahjong on Tuesday. Lily Lee taught us in 1949 and has regretted it every week since.",
      "Isaac will close on Saturdays the day after the Messiah comes. He'll want to fit him first.",
      "Samuel came home from Germany in '45 and cut cloth for six months without a word. Then one day he laughed at something on the radio. I sat down on the kitchen floor and cried.",
    ] },
  { first: 'Samuel', last: 'Adler', age: 41, sex: 'M', role: 'shopkeeper', job: { building: 'Adler & Son, Tailors', role: 'tailor' }, look: lk(SK.light, HC.dark, FC.glasses, HS.part),
    bio: "Samuel Adler, 41, the “& Son” of Adler & Son, Tailors. Served with the Army in Germany in 1945 and came home quiet. Made Robert Brennan's wedding suit — three fittings, because the groom kept losing weight from nerves. Still a bachelor, which his mother mentions.",
    lines: [
      "Robert Brennan's suit: three fittings. He lost four pounds from nerves between the second and the third. I took it in. Love is hard on tailoring.",
      "Pop still won't let me cut the Mayor's trousers. I'm forty-one. I've been the “& Son” since 1934.",
      "I was in Germany in '45. I saw what I saw. Now I make suits, and I'm glad every single day of it.",
      "Ma wants me married. I tell her I'm married to the shop. She says the shop doesn't make kugel.",
    ] },
  // ------------------------------------------------------------------ the Brennans (fire captain, the groom)
  { first: 'Joe', last: 'Brennan', age: 52, sex: 'M', title: 'Captain', role: 'fire', outfit: 'fire', job: { building: 'Engine Company No. 1', role: 'captain' }, look: lk(SK.fair, HC.salt, FC.mustache, HS.short),
    bio: "Captain Joseph Brennan, 52 — “Chief” to the whole town — commands Engine Company No. 1 (telephone 2-1100; ask for Joe; bring the TALL ladder). Father of the groom. Has spent the morning polishing brass, will spend eleven o'clock rescuing Mrs. Hatch's cat for the fifth time since Easter, and two o'clock trying not to cry at St. Brigid's. His kid brother Tommy is on the World War II honor roll.",
    lines: [
      "My boy gets married at two and I'm on the cat detail at eleven. Some Saturday.",
      "Old Faithful came in 1903, the year after the fire. The town swore it'd never be caught short again. She still shines, doesn't she?",
      "Admiral. Five times since Easter. That cat knows my ladder better than my men do.",
      "Robert set his own wedding notice in type and checked it nine times. Makes a fine linotype man and would've made a terrible fireman.",
      "Two pumpers on the quay tonight for the fireworks, just in case. Ask me sometime about the night the Custom House caught fire. Actually — don't.",
      "My kid brother Tommy's on the board at City Hall. I'll be thinking about him at two o'clock. He'd have been the best man. He'd have been a terrible best man. I miss him.",
    ] },
  { first: 'Nora', last: 'Brennan', age: 50, sex: 'F', title: 'Mrs.', formal: true, look: lk(SK.fair, HC.brown, FC.lipstick, HS.curly),
    bio: "Nora Brennan, 50, mother of the groom and wife of Captain Joe. Has been crying, on and off, since Wednesday. Bakes soda bread for the firehouse every Friday and considers the men of Engine Co. No. 1 her other sons. Wants a yellow corsage. Stella Novak says NO yellow.",
    lines: [
      "I'm not crying. It's the chrysanthemums. The Bower girls put chrysanthemums everywhere.",
      "Stella Novak says no yellow corsage. It's my son's wedding too. I'm wearing a little yellow. A little.",
      "Every Friday I bake for the firehouse. Twelve men, twelve loaves. Joe says they fight fires on it.",
      "Madame Gould made me a navy straw. “Nothing that competes with Stella,” I told her. I'm a very generous woman.",
      "Robert was a colicky baby and a careful boy and he's going to be a good husband. Somebody hand me a handkerchief.",
    ] },
  { first: 'Robert', last: 'Brennan', age: 26, sex: 'M', role: 'groom', outfit: 'groom', job: { building: 'The Juniper Bay Courier', role: 'linotype' }, look: lk(SK.fair, HC.brown, FC.plain, HS.part),
    bio: "Robert Joseph Brennan, 26, linotype operator at the Courier, of Church Street. Marries Helen Novak at St. Brigid's at two o'clock. Set the type for his own wedding announcement and checked it nine times. Bought the ring from Jacob Weiss at two dollars a week; Mr. Weiss engraved it for nothing, by lamplight, last night. A maple bedroom suite is on layaway at Tremblay's, to be delivered “after the honeymoon. Don't come early.”",
    lines: [
      "I set the type for our own wedding announcement. Checked it nine times.",
      "Mr. Weiss engraved the ring for nothing. “For a centennial bride,” he said. I'm paying the rest at two dollars a week till June.",
      "The Adlers took my suit in three times. I keep losing weight. Pop says it's nerves. It's nerves.",
      "Miss Lowell gave me the day off. First Saturday in four years — the presses will have to roll the Centennial edition without me. They'll manage. Probably.",
      "Helen keeps the cannery's books to the penny. I set type to the letter. Our children are going to be very tidy.",
    ] },
  { first: 'Mary', last: 'Brennan', age: 19, sex: 'F', look: lk(SK.fair, HC.red, FC.freckles, HS.curly),
    bio: "Mary Brennan, 19, the groom's sister — “the Brennan girl” in Mrs. Silva's alterations book (“fine”). Bridesmaid in pink taffeta, typing student at Pratt Secretarial School on Saturday mornings, and the only person in the family who is not crying.",
    lines: [
      "Bridesmaid at two. Pink taffeta. Mrs. Silva wrote “fine” next to my name. FINE. I'll take it.",
      "Miss Pratt said the centennial is not an excuse, so I typed forty words a minute this morning in a bridesmaid's hairdo.",
      "Ma's crying, Pa's crying, Robert's crying. Somebody in this family has to hold the bouquet.",
      "Helen's my best friend now, officially. She was already. Now there's paperwork.",
    ] },
  // ------------------------------------------------------------------ the Duffys (police desk, St. Luke's)
  { first: 'Augustine', last: 'Duffy', age: 57, sex: 'M', title: 'Sergeant', role: 'police', outfit: 'police', job: { building: 'Police Headquarters', role: 'desk sergeant' }, look: lk(SK.fair, HC.gray, FC.mustache, HS.short),
    bio: "Sergeant Augustine “Augie” Duffy, 57, desk sergeant at Police Headquarters since 1936 and Irene Halloran's older brother. His mother, Nurse Honora Duffy, never left the council-chamber ward in the 1918 influenza; his brother Francis fell in the Argonne that October; his son Jimmy was killed in France in 1944. His daughter Theresa came home from Anzio. Keeps a jar of peppermints for lost children and a ledger of every lost wallet returned since 1936.",
    lines: [
      "Lost child, lost dog, lost wallet. Centennial day. Take a number.",
      "Fourteen hundred and twelve wallets returned since '36. Honest town. Mostly honest. Mostly wallets.",
      "My kid sister Irene's pie had better win. I'm not saying I'd arrest the judges. I'm saying I know where they park.",
      "Duffys go when they're called. My brother Francis in 1918. My boy Jimmy in '44. Theresa came home. I light two candles and thank God for the third.",
      "My mother nursed in the council chamber in 1918 for six weeks and never went home. There's a plaque. She'd have hated the plaque.",
      "Peppermint? I keep them for lost children. You look a little lost.",
    ] },
  { first: 'Theresa', last: 'Duffy', age: 34, sex: 'F', title: 'Nurse', role: 'nurse', outfit: 'nurse', job: { building: "St. Luke's Hospital", role: 'nurse' }, look: lk(SK.fair, HC.auburn, FC.plain, HS.bob),
    bio: "Theresa Duffy, R.N., 34, Sergeant Duffy's daughter and granddaughter of Nurse Honora Duffy of the 1918 ward. Served as an Army nurse at the Anzio beachhead in 1944, where she held the hand of a Juniper Bay boy named George Crowell, and wrote his mother the letter Agnes Crowell still reads every Memorial Day. Now charge nurse on the maternity ward at St. Luke's, where Carol Kaminski has been since midnight.",
    lines: [
      "Mrs. Kaminski is doing fine. Mr. Kaminski is not. Would somebody please take him for a walk?",
      "I was at Anzio in '44. I don't talk about much of it. I wrote to Agnes Crowell about her George. That, I'll talk about. He was brave and he wasn't alone.",
      "Grandmother Honora never left the council chamber for six weeks in 1918. When things are bad on the ward I think: six weeks. I can do one more hour.",
      "Maria Castellano is going to make a fine nurse. She doesn't faint and she doesn't gossip. That's ninety percent of it.",
      "Visiting hours end at eight. Yes, even for the fireworks. Especially for the fireworks.",
    ] },
  // ------------------------------------------------------------------ the Rourkes (the Market Street beat, the paperboy)
  { first: 'Frank', last: 'Rourke', age: 44, sex: 'M', title: 'Officer', role: 'police', outfit: 'police', job: { building: 'Police Headquarters', role: 'patrolman' }, look: lk(SK.fair, HC.dark, FC.smile, HS.short),
    bio: "Officer Frank Rourke, 44, walks the Market Street beat and knows every dog, doorway and doorstep on it by name. Twenty-two years on the force; waded Harbor Street in the '38 hurricane pulling people off porches, among them Wendell Carver's grandsons. Walks Lonnie Tobey home from the Signal Lamp most nights, says he's going that way, and never writes it down.",
    lines: [
      "Evening. Keep to the sidewalk — the fireworks crowd'll be thick tonight.",
      "Twenty-two years on this beat. Seen the hurricane, seen V-J Day. Never seen a turnout like today.",
      "In '38 I pulled the Carver boys off a porch on Harbor Street in water up to my chest. They're grown now. They still wave.",
      "Lonnie Tobey? He's all right. I walk him home some nights. It's a short walk and a long story.",
      "My boy Petey delivers the Courier. Knows every porch on Maple Street better than I do.",
    ] },
  { first: 'Petey', last: 'Rourke', age: 12, sex: 'M', look: lk(SK.fair, HC.red, FC.freckles, HS.buzz, { hat: 'hat_cap', hatTint: '#8a2a2a' }),
    bio: "Peter “Petey” Rourke, 12, the Courier's paperboy on the Maple and Orchard Street route: ninety-one papers, six days a week, on a bicycle whose chain comes off at the corner of Elm. Knows which porches have dogs, which have tips, and which have Mrs. Hatch.",
    lines: [
      "Ninety-one papers! Sunday's forty-eight pages. I'm gonna need a bigger bag and a bigger me.",
      "Mrs. Hatch tips a dime at Christmas and a lecture every other day of the year.",
      "Tomorrow's headline's a secret. Robert Brennan tells me stuff, though. It's got “SEA” in it. That's all I'm saying.",
      "Pa walks the beat, I walk the route. He says between us we've got the whole town covered.",
      "Skippy Mercer ran my whole route with me Thursday. Just ran it. Didn't carry anything. Just ran.",
    ] },
  // ------------------------------------------------------------------ the Garritys (St. Brigid's, the hardware store)
  { first: 'Francis', last: 'Garrity', own: true, age: 63, sex: 'M', title: 'Father', role: 'clergy', outfit: 'clergy', home: { name: "St. Brigid's Rectory & Parish Hall" }, job: { building: "St. Brigid's Church", role: 'priest' }, look: lk(SK.fair, HC.white, FC.glasses, HS.short),
    bio: "Father Francis X. Garrity, 63, pastor of St. Brigid's since 1931. Grew up in the rooms over his father's hardware store on Canal Street; his brother Tom runs it now. Blesses the fleet every June, hears confessions every Saturday at four, and marries Helen Novak and Robert Brennan at two today. Plays checkers with the Reverend Ashby on Tuesdays. Judged the 1949 pie contest, swore never again, and has been talked into judging today by Mrs. Pemberton.",
    lines: [
      "A wedding at two, confessions at four, and the Castellanos have invited me to supper. God is good.",
      "I judged the pie contest in 1949 and swore never again. Mrs. Pemberton asked. Nobody refuses Mrs. Pemberton. Pray for me.",
      "Theodore Ashby and I play checkers Tuesdays. He accuses me of cheating. A Congregationalist wouldn't understand the finer points.",
      "My brother Tom swears the Halloran boy was out at home. I was there. He was safe. Tom says I need spectacles. I say Tom needs confession.",
      "The bell came from Troy in 1884. It rang for an hour on V-J Day, till the rope broke. It rings at three today for Helen and Robert. We've a new rope.",
      "Every June I bless the fleet. Three Castellano boats and a hundred others. I pray they need it less than I fear.",
    ] },
  { first: 'Tom', last: 'Garrity', age: 60, sex: 'M', role: 'shopkeeper', home: { name: 'Garrity Hardware' }, job: { building: 'Garrity Hardware', role: 'proprietor' }, look: lk(SK.fair, HC.gray, FC.glassesMustache, HS.part),
    bio: "Tom Garrity, 60, proprietor of Garrity Hardware, which his father Michael opened in 1904 with a wagonload of nails for the men rebuilding Market Street after the fire; the first dollar is framed by the register. Father Garrity's younger brother. Coaches the Garrity Hardware Little League nine, which lost 7–6 last Saturday to Castellano Fish Co. on a steal of home Tom maintains to this day was an out. Lost his son Michael in the war.",
    lines: [
      "That Halloran kid was OUT. By a foot. I've got witnesses. I've got a brother who's a priest, but he's no help.",
      "Pop opened in 1904 selling nails to the men who rebuilt Market Street. First dollar's on the wall. “Pop says never spend it.” We never have.",
      "In '32 Pop carried half this street on the books. “Pay when you can,” he'd write. The last of them paid in 1941. Came in with the money in an envelope and cried.",
      "First prize in the pie contest is a Mixmaster from my store. If Irene Halloran wins it, it's going to a house that sells me my bread. Circle of life.",
      "Television antennas — can't keep them on the shelf. Vic DeLuca buys 'em by the dozen.",
    ] },
  { first: 'Kathleen', last: 'Garrity', age: 56, sex: 'F', title: 'Mrs.', look: lk(SK.fair, HC.salt, FC.glassesLipstick, HS.bob),
    bio: "Kathleen Garrity, 56, keeps the books at the hardware store and the peace at home. A Brennan cousin on her mother's side, which makes this afternoon's wedding practically a family reunion. Lost her son Michael in the war; has a younger son, Kevin, in the Air Force in Texas.",
    lines: [
      "Tom will tell you that boy was out until the Second Coming. My brother-in-law the priest says safe. I keep the books and stay out of it.",
      "I'm a Brennan on my mother's side, so Robert's my cousin some way. In this town everybody's your cousin some way.",
      "My Michael is on the board at City Hall. Kevin's in Texas with the Air Force. Every time a plane goes over I look up. Every single time.",
      "Pharmacist Mayhew says I'm to take my pills with water, not coffee. I've been taking them with coffee for eleven years and I'm still here.",
    ] },
  // @@NOTABLES@@
];
